#!/usr/bin/env python3
"""Generate glossary.ts with 150 glossary terms."""

TERMS = [
    # AI Fundamentals (30)
    ("large-language-model", "Large Language Model (LLM)", "A neural network trained on massive text datasets to understand and generate human language.", "Large Language Models are the foundation of modern AI assistants like ChatGPT and Claude. They use transformer architecture trained on billions of text tokens to learn language patterns, reasoning, and knowledge. LLMs power everything from chatbots to code generation.", ["transformer", "fine-tuning", "prompt-engineering"], "AI Fundamentals"),
    ("artificial-intelligence", "Artificial Intelligence (AI)", "The simulation of human intelligence by computer systems capable of learning, reasoning, and problem-solving.", "Artificial Intelligence encompasses machine learning, deep learning, and natural language processing. Modern AI systems can generate text, images, code, and music. The field has accelerated dramatically with large language models.", ["machine-learning", "deep-learning", "neural-network"], "AI Fundamentals"),
    ("machine-learning", "Machine Learning (ML)", "A subset of AI where systems learn from data to improve performance without explicit programming.", "Machine learning algorithms identify patterns in data to make predictions and decisions. Types include supervised, unsupervised, and reinforcement learning. ML powers recommendation systems, fraud detection, and predictive analytics.", ["deep-learning", "supervised-learning", "artificial-intelligence"], "AI Fundamentals"),
    ("deep-learning", "Deep Learning", "A subset of machine learning using multi-layered neural networks to learn complex patterns from data.", "Deep learning enables AI to process images, speech, and text with human-like accuracy. It uses architectures like CNNs for vision and transformers for language. Deep learning requires large datasets and significant compute resources.", ["neural-network", "machine-learning", "transformer"], "AI Fundamentals"),
    ("neural-network", "Neural Network", "A computing system inspired by biological neural networks that learns to recognize patterns in data.", "Neural networks consist of layers of interconnected nodes that process information. They learn by adjusting connection weights during training. Modern deep neural networks can have billions of parameters.", ["deep-learning", "machine-learning", "transformer"], "AI Fundamentals"),
    ("transformer", "Transformer", "The neural network architecture behind modern LLMs using self-attention mechanisms for parallel processing.", "Introduced in the 2017 paper Attention Is All You Need, transformers revolutionized NLP by processing entire sequences in parallel rather than sequentially. They power GPT, Claude, Gemini, and virtually all modern language models.", ["large-language-model", "neural-network", "deep-learning"], "AI Fundamentals"),
    ("natural-language-processing", "Natural Language Processing (NLP)", "The field of AI focused on enabling computers to understand, interpret, and generate human language.", "NLP combines linguistics and machine learning to process text and speech. Applications include translation, sentiment analysis, chatbots, and content generation. Modern NLP is dominated by transformer-based models.", ["large-language-model", "transformer", "artificial-intelligence"], "AI Fundamentals"),
    ("computer-vision", "Computer Vision", "AI systems that interpret and understand visual information from images and videos.", "Computer vision enables AI to detect objects, recognize faces, read text, and understand scenes. Applications include autonomous driving, medical imaging, and quality inspection. Deep learning has dramatically improved CV accuracy.", ["deep-learning", "neural-network", "artificial-intelligence"], "AI Fundamentals"),
    ("reinforcement-learning", "Reinforcement Learning (RL)", "An ML paradigm where agents learn optimal behavior through trial-and-error interactions with environments.", "Reinforcement learning trains AI by rewarding desired behaviors and penalizing undesired ones. It powers game-playing AI, robotics, and recommendation systems. RLHF is used to align language models with human preferences.", ["machine-learning", "artificial-intelligence", "ai-alignment"], "AI Fundamentals"),
    ("generative-ai", "Generative AI", "AI systems that create new content including text, images, code, audio, and video from prompts.", "Generative AI has transformed content creation by enabling AI to produce human-quality outputs. Key technologies include LLMs for text, diffusion models for images, and neural codecs for audio. It powers tools like ChatGPT, Midjourney, and Suno.", ["large-language-model", "artificial-intelligence", "foundation-model"], "AI Fundamentals"),
    ("foundation-model", "Foundation Model", "Large-scale AI models trained on broad data that can be adapted to many downstream tasks.", "Foundation models like GPT-4, Claude, and Gemini are trained on diverse datasets and serve as the base for many applications. They can be fine-tuned or prompted for specific tasks without retraining from scratch.", ["large-language-model", "generative-ai", "fine-tuning"], "AI Fundamentals"),
    ("multi-modal-ai", "Multimodal AI", "AI systems that process and generate multiple types of data including text, images, audio, and video.", "Multimodal AI can understand images and text together, generate images from descriptions, and transcribe audio to text. Models like GPT-4V and Gemini exemplify multimodal capabilities.", ["generative-ai", "computer-vision", "natural-language-processing"], "AI Fundamentals"),
    ("artificial-general-intelligence", "Artificial General Intelligence (AGI)", "Hypothetical AI with human-level reasoning across all cognitive domains without task-specific training.", "AGI remains an aspirational goal in AI research. Current AI systems are narrow — excelling at specific tasks but lacking general reasoning. The timeline for AGI is debated, with estimates ranging from years to decades.", ["artificial-intelligence", "ai-alignment", "ai-safety"], "AI Fundamentals"),
    ("supervised-learning", "Supervised Learning", "ML approach where models learn from labeled examples to predict outcomes for new inputs.", "Supervised learning uses input-output pairs to train models for classification and regression tasks. Common applications include spam detection, image recognition, and price prediction. It requires high-quality labeled training data.", ["machine-learning", "deep-learning", "training-data"], "AI Fundamentals"),
    ("unsupervised-learning", "Unsupervised Learning", "ML approach where models find patterns in unlabeled data without predefined categories.", "Unsupervised learning discovers hidden structures in data through clustering, dimensionality reduction, and anomaly detection. Applications include customer segmentation, topic modeling, and fraud detection.", ["machine-learning", "deep-learning", "training-data"], "AI Fundamentals"),
    ("transfer-learning", "Transfer Learning", "Technique of applying knowledge learned from one task to improve performance on a different task.", "Transfer learning allows models pre-trained on large datasets to be fine-tuned for specific tasks with much less data. This approach powers most modern AI applications by building on foundation models.", ["fine-tuning", "foundation-model", "machine-learning"], "AI Fundamentals"),
    ("few-shot-learning", "Few-Shot Learning", "The ability of AI models to learn new tasks from only a few examples provided in the prompt.", "Few-shot learning enables LLMs to perform new tasks by showing a handful of input-output examples in the prompt context. This eliminates the need for task-specific training data and enables rapid prototyping.", ["prompt-engineering", "large-language-model", "zero-shot-learning"], "AI Fundamentals"),
    ("zero-shot-learning", "Zero-Shot Learning", "AI's ability to perform tasks it wasn't explicitly trained for without any examples.", "Zero-shot learning allows models to generalize to new tasks using only natural language instructions. Modern LLMs demonstrate strong zero-shot capabilities across diverse tasks like translation, summarization, and classification.", ["few-shot-learning", "large-language-model", "prompt-engineering"], "AI Fundamentals"),
    ("federated-learning", "Federated Learning", "ML technique that trains models across distributed devices without sharing raw data.", "Federated learning enables AI training on sensitive data by keeping data local and only sharing model updates. Used in healthcare, mobile keyboards, and enterprise AI where data privacy is paramount.", ["machine-learning", "ai-safety", "ai-governance"], "AI Fundamentals"),
    ("edge-ai", "Edge AI", "Running AI models directly on local devices rather than in the cloud for faster response times.", "Edge AI processes data on devices like phones, IoT sensors, and embedded systems. Benefits include lower latency, offline capability, and enhanced privacy. Techniques like quantization make large models run on smaller devices.", ["artificial-intelligence", "quantization", "inference"], "AI Fundamentals"),
    ("ai-alignment", "AI Alignment", "The research field focused on ensuring AI systems behave in accordance with human values and intentions.", "AI alignment addresses the challenge of making AI systems do what humans actually want, not just what they're literally instructed to do. Key approaches include RLHF, constitutional AI, and interpretability research.", ["ai-safety", "ai-ethics", "reinforcement-learning"], "AI Fundamentals"),
    ("ai-safety", "AI Safety", "Research and practices ensuring AI systems operate reliably and don't cause unintended harm.", "AI safety encompasses alignment, robustness, monitoring, and containment of AI systems. It's increasingly important as AI becomes more capable. Key concerns include hallucination, misuse, and emergent behaviors.", ["ai-alignment", "ai-ethics", "guardrails"], "AI Fundamentals"),
    ("explainable-ai", "Explainable AI (XAI)", "AI systems that provide human-understandable explanations for their decisions and predictions.", "Explainable AI addresses the black box problem by making model reasoning transparent. Important for regulated industries like healthcare and finance where decisions must be justified and auditable.", ["artificial-intelligence", "ai-governance", "ai-ethics"], "AI Fundamentals"),
    ("responsible-ai", "Responsible AI", "Framework for developing AI systems that are fair, transparent, accountable, and beneficial.", "Responsible AI encompasses bias mitigation, transparency, privacy protection, and societal impact assessment. Organizations implement responsible AI through governance frameworks, auditing, and ethical review processes.", ["ai-ethics", "ai-governance", "ai-safety"], "AI Fundamentals"),
    ("ai-ethics", "AI Ethics", "The moral principles and guidelines governing the development and use of artificial intelligence.", "AI ethics addresses fairness, bias, privacy, transparency, accountability, and societal impact. Key debates include AI's effect on employment, creative ownership, and the digital divide.", ["responsible-ai", "ai-governance", "ai-alignment"], "AI Fundamentals"),
    ("ai-governance", "AI Governance", "Policies, processes, and standards for managing AI development and deployment responsibly.", "AI governance frameworks define who can build AI, what data can be used, how models are tested, and who is accountable for outcomes. The EU AI Act is a landmark governance regulation.", ["ai-ethics", "responsible-ai", "ai-regulation"], "AI Fundamentals"),
    ("ai-regulation", "AI Regulation", "Government laws and policies regulating the development, deployment, and use of AI systems.", "Key regulations include the EU AI Act, China's AI regulations, and US executive orders on AI safety. Regulations address risk classification, transparency requirements, and accountability standards.", ["ai-governance", "ai-ethics", "responsible-ai"], "AI Fundamentals"),

    # AI Engineering (30)
    ("prompt-engineering", "Prompt Engineering", "The practice of designing effective instructions and context for AI models to generate desired outputs.", "Prompt engineering is a critical skill for getting the best results from LLMs. Techniques include chain-of-thought prompting, few-shot examples, system prompts, and structured output formatting.", ["large-language-model", "chain-of-thought", "few-shot-learning"], "AI Engineering"),
    ("fine-tuning", "Fine-Tuning", "The process of further training a pre-trained AI model on specific data for improved task performance.", "Fine-tuning adapts foundation models to specific domains, tasks, or styles. Methods include full fine-tuning, LoRA, and QLoRA. It requires curated training data but produces models specialized for your use case.", ["foundation-model", "transfer-learning", "training-data"], "AI Engineering"),
    ("retrieval-augmented-generation", "Retrieval-Augmented Generation (RAG)", "AI technique that enhances LLM responses by retrieving relevant context from external knowledge bases.", "RAG combines the generative power of LLMs with the accuracy of information retrieval. Documents are chunked, embedded into vectors, and stored in vector databases. At query time, relevant chunks are retrieved and fed to the LLM.", ["vector-database", "embedding", "large-language-model"], "AI Engineering"),
    ("vector-database", "Vector Database", "A database optimized for storing and querying high-dimensional vector embeddings for similarity search.", "Vector databases power RAG systems, recommendation engines, and semantic search. They store document embeddings and find similar content using approximate nearest neighbor algorithms. Popular options include Pinecone, Weaviate, and Chroma.", ["embedding", "retrieval-augmented-generation", "vector-store"], "AI Engineering"),
    ("embedding", "Embedding", "A numerical vector representation of data that captures semantic meaning for machine processing.", "Embeddings convert text, images, and other data into dense vectors where similar items are close together in vector space. They enable semantic search, clustering, and recommendation systems.", ["vector-database", "retrieval-augmented-generation", "tokenization"], "AI Engineering"),
    ("tokenization", "Tokenization", "The process of breaking text into smaller units called tokens that AI models can process.", "Tokenization converts human-readable text into numerical token sequences that LLMs process. Different models use different tokenizers. Token count affects pricing, context window usage, and processing speed.", ["large-language-model", "context-window", "embedding"], "AI Engineering"),
    ("context-window", "Context Window", "The maximum amount of text an AI model can process in a single conversation or prompt.", "Context windows determine how much information an LLM can consider at once. Modern models range from 8K to 1M+ tokens. Larger context windows enable processing entire codebases or long documents.", ["large-language-model", "tokenization", "prompt-engineering"], "AI Engineering"),
    ("temperature", "Temperature", "A parameter controlling the randomness and creativity of AI model outputs.", "Temperature ranges from 0 (deterministic) to 2 (highly random). Lower temperatures produce focused, consistent outputs ideal for factual tasks. Higher temperatures increase creativity and variation.", ["large-language-model", "top-p-sampling", "prompt-engineering"], "AI Engineering"),
    ("top-p-sampling", "Top-P Sampling", "A decoding strategy that limits token selection to the most probable options summing to probability P.", "Also called nucleus sampling, top-p filtering dynamically adjusts the number of candidate tokens based on their cumulative probability. Combined with temperature, it controls output diversity.", ["temperature", "large-language-model", "prompt-engineering"], "AI Engineering"),
    ("chain-of-thought", "Chain of Thought (CoT)", "A prompting technique that improves AI reasoning by asking models to show step-by-step thinking.", "Chain of thought prompting significantly improves LLM performance on math, logic, and complex reasoning tasks. Variants include zero-shot CoT and self-consistency CoT.", ["prompt-engineering", "large-language-model", "few-shot-learning"], "AI Engineering"),
    ("tool-use", "Tool Use", "The ability of AI models to call external tools, APIs, and functions to accomplish tasks.", "Tool use extends AI capabilities beyond text generation to actions like web search, code execution, database queries, and API calls. It's fundamental to building useful AI agents.", ["function-calling", "ai-agent", "large-language-model"], "AI Engineering"),
    ("function-calling", "Function Calling", "AI model capability to generate structured function calls based on natural language instructions.", "Function calling allows LLMs to output structured JSON that maps to predefined functions. It enables reliable tool use, form filling, and structured data extraction from natural language.", ["tool-use", "ai-agent", "large-language-model"], "AI Engineering"),
    ("model-distillation", "Model Distillation", "Training a smaller model to replicate the behavior of a larger teacher model for efficiency.", "Knowledge distillation transfers capabilities from large models to smaller, faster ones. This enables deploying powerful AI on edge devices and reducing inference costs while maintaining quality.", ["fine-tuning", "quantization", "inference"], "AI Engineering"),
    ("quantization", "Quantization", "Reducing AI model precision from 32-bit to 8-bit or 4-bit to decrease size and speed up inference.", "Quantization enables large models to run on consumer hardware by reducing memory requirements. Methods like GPTQ and GGUF maintain most model quality while dramatically reducing resource needs.", ["model-distillation", "inference", "edge-ai"], "AI Engineering"),
    ("inference", "Inference", "The process of running a trained AI model to generate predictions or outputs from new inputs.", "Inference is when AI models process user queries and generate responses. Inference speed, cost, and quality are key considerations for production AI systems. Batching and caching optimize inference efficiency.", ["model-serving", "latency-optimization", "throughput"], "AI Engineering"),
    ("training-data", "Training Data", "The dataset used to train AI models, directly impacting model capabilities and biases.", "Training data quality determines AI model performance. Issues include bias, data poisoning, copyright, and representation. Curation, cleaning, and documentation of training data are critical practices.", ["fine-tuning", "supervised-learning", "machine-learning"], "AI Engineering"),
    ("hallucination", "Hallucination", "When AI models generate plausible-sounding but factually incorrect or fabricated information.", "Hallucinations occur because LLMs generate statistically likely text rather than verified facts. Mitigation strategies include RAG, grounding, source citation, and chain-of-thought verification.", ["grounding", "retrieval-augmented-generation", "guardrails"], "AI Engineering"),
    ("grounding", "Grounding", "Techniques for connecting AI outputs to verified information sources to reduce hallucinations.", "Grounding ensures AI responses are based on factual sources rather than model training alone. RAG, web search, database lookups, and tool use are common grounding techniques.", ["hallucination", "retrieval-augmented-generation", "guardrails"], "AI Engineering"),
    ("guardrails", "Guardrails", "Safety mechanisms that constrain AI behavior to prevent harmful, incorrect, or off-topic outputs.", "Guardrails include input validation, output filtering, topic restriction, PII detection, and content safety checks. They're essential for production AI systems to maintain quality and safety.", ["ai-safety", "hallucination", "grounding"], "AI Engineering"),
    ("red-teaming", "Red Teaming", "Systematic adversarial testing of AI systems to identify vulnerabilities and failure modes.", "Red teaming involves deliberately trying to make AI systems produce harmful, biased, or incorrect outputs. It's a critical safety practice before deploying AI systems to production.", ["ai-safety", "guardrails", "ai-alignment"], "AI Engineering"),
    ("ai-agent", "AI Agent", "An AI system that autonomously plans, reasons, and takes actions to accomplish goals.", "AI agents go beyond simple chat by using tools, making decisions, and executing multi-step plans. Frameworks like LangGraph and CrewAI enable building agents. Key challenges include reliability and safety.", ["multi-agent-system", "tool-use", "orchestration"], "AI Engineering"),
    ("multi-agent-system", "Multi-Agent System", "AI architecture where multiple specialized agents collaborate to solve complex tasks.", "Multi-agent systems assign different roles to different AI agents that communicate and coordinate. Examples include coding agents with separate planning, implementation, and review agents.", ["ai-agent", "orchestration", "ai-squad"], "AI Engineering"),
    ("orchestration", "Orchestration", "Managing the coordination, sequencing, and data flow between multiple AI components or agents.", "Orchestration frameworks handle routing between agents, managing shared state, error recovery, and human-in-the-loop checkpoints. LangGraph and CrewAI are popular orchestration tools.", ["multi-agent-system", "ai-agent", "model-serving"], "AI Engineering"),
    ("model-serving", "Model Serving", "Infrastructure for deploying and running AI models in production to handle user requests.", "Model serving handles load balancing, scaling, versioning, and monitoring of deployed AI models. Options range from managed APIs to self-hosted solutions using tools like vLLM and TGI.", ["inference", "latency-optimization", "throughput"], "AI Engineering"),
    ("batch-inference", "Batch Inference", "Processing multiple AI requests together for improved throughput and reduced per-request cost.", "Batch inference is ideal for non-real-time tasks like content generation, data processing, and bulk analysis. It offers 50% or more cost savings compared to real-time inference.", ["inference", "throughput", "model-serving"], "AI Engineering"),
    ("streaming", "Streaming", "Delivering AI model outputs token-by-token as they're generated rather than waiting for completion.", "Streaming provides better user experience by showing responses progressively. Most modern AI APIs support server-sent events for streaming. It's essential for chat interfaces.", ["inference", "latency-optimization", "model-serving"], "AI Engineering"),
    ("latency-optimization", "Latency Optimization", "Techniques for reducing the time between an AI request and response delivery.", "Latency optimization includes model quantization, response caching, edge deployment, prompt optimization, and streaming. Target latencies vary by use case from milliseconds to seconds.", ["inference", "streaming", "throughput"], "AI Engineering"),
    ("throughput", "Throughput", "The number of AI requests or tokens a system can process per unit of time.", "Throughput measures system capacity for handling concurrent AI requests. Optimization strategies include batching, model parallelism, and efficient infrastructure scaling.", ["inference", "latency-optimization", "batch-inference"], "AI Engineering"),
    ("benchmark", "Benchmark", "Standardized tests used to evaluate and compare AI model performance across specific capabilities.", "Popular benchmarks include MMLU for knowledge, HumanEval for coding, and MT-Bench for conversation. Benchmarks help compare models but may not reflect real-world performance.", ["evaluation-metrics", "large-language-model", "inference"], "AI Engineering"),
    ("evaluation-metrics", "Evaluation Metrics", "Measurements used to assess AI model quality including accuracy, perplexity, and human preference.", "AI evaluation uses automated metrics (BLEU, ROUGE, perplexity) and human evaluation. For LLMs, human preference ratings and task-specific benchmarks are most meaningful.", ["benchmark", "large-language-model", "training-data"], "AI Engineering"),

    # AI Business (25)
    ("ai-as-a-service", "AI as a Service (AIaaS)", "Cloud-based AI capabilities accessible via APIs without managing underlying infrastructure.", "AIaaS enables businesses to add AI capabilities like text generation, image analysis, and speech recognition through simple API calls. Major providers include OpenAI, Anthropic, and Google.", ["artificial-intelligence", "model-serving", "inference"], "AI Business"),
    ("mlops", "MLOps", "Practices for deploying, monitoring, and maintaining machine learning models in production.", "MLOps combines ML engineering and DevOps to streamline the ML lifecycle. It covers model versioning, deployment pipelines, monitoring, retraining, and A/B testing of models.", ["ai-ops", "model-serving", "inference"], "AI Business"),
    ("ai-ops", "AIOps", "Using AI to automate and improve IT operations including monitoring, alerting, and incident management.", "AIOps applies machine learning to IT operations data for intelligent alerting, root cause analysis, and automated remediation. It reduces alert fatigue and improves incident response.", ["mlops", "artificial-intelligence", "orchestration"], "AI Business"),
    ("ai-squad", "AI Squad", "A team of specialized AI agents coordinated by a human expert to deliver production software.", "ShipSquad's AI squad model pairs one dedicated human expert with 8 specialized AI agents covering architecture, frontend, backend, QA, DevOps, review, decomposition, and communication.", ["multi-agent-system", "ai-agent", "orchestration"], "AI Business"),
    ("ai-automation", "AI Automation", "Using AI to automate business processes, decisions, and workflows that previously required human judgment.", "AI automation goes beyond rule-based automation by handling unstructured data, making context-aware decisions, and learning from outcomes. It powers everything from email sorting to loan approvals.", ["robotic-process-automation", "ai-agent", "artificial-intelligence"], "AI Business"),
    ("robotic-process-automation", "Robotic Process Automation (RPA)", "Software bots that automate repetitive digital tasks by mimicking human interactions with applications.", "RPA handles tasks like data entry, form filling, and system navigation. When combined with AI, it can handle unstructured data and make decisions, evolving into intelligent automation.", ["ai-automation", "artificial-intelligence", "ai-ops"], "AI Business"),
    ("intelligent-document-processing", "Intelligent Document Processing (IDP)", "AI-powered extraction of data from unstructured documents like invoices, contracts, and forms.", "IDP uses OCR, NLP, and machine learning to read and understand documents. It extracts key information, validates data, and routes documents for processing.", ["natural-language-processing", "ai-automation", "artificial-intelligence"], "AI Business"),
    ("conversational-ai", "Conversational AI", "AI systems designed for natural human-like dialogue including chatbots and virtual assistants.", "Conversational AI powers customer support chatbots, virtual assistants, and interactive voice response systems. Modern conversational AI uses LLMs for natural, context-aware responses.", ["natural-language-processing", "ai-agent", "large-language-model"], "AI Business"),
    ("ai-copilot", "AI Copilot", "An AI assistant that works alongside humans to augment their capabilities and productivity.", "AI copilots provide suggestions, automate routine tasks, and assist with decision-making while keeping humans in control. Examples include GitHub Copilot for code and Microsoft 365 Copilot for documents.", ["ai-assistant", "ai-augmentation", "tool-use"], "AI Business"),
    ("ai-assistant", "AI Assistant", "An AI system designed to help users complete tasks through natural language interaction.", "AI assistants like ChatGPT, Claude, and Gemini help with writing, analysis, coding, research, and creative tasks. They differ from agents in that they respond to requests rather than acting autonomously.", ["conversational-ai", "ai-copilot", "large-language-model"], "AI Business"),
    ("autonomous-agent", "Autonomous Agent", "An AI system that can independently plan and execute tasks with minimal human supervision.", "Autonomous agents go beyond assistants by making decisions, using tools, and completing multi-step tasks independently. Examples include Devin for coding and AI customer support agents.", ["ai-agent", "multi-agent-system", "tool-use"], "AI Business"),
    ("human-in-the-loop", "Human-in-the-Loop (HITL)", "AI workflow design where humans review, approve, or correct AI outputs at key decision points.", "HITL ensures quality and safety by keeping humans involved in critical AI decisions. It's essential for high-stakes applications like healthcare, legal, and financial AI systems.", ["ai-safety", "ai-agent", "responsible-ai"], "AI Business"),
    ("ai-augmentation", "AI Augmentation", "Using AI to enhance human capabilities rather than replace human workers entirely.", "AI augmentation focuses on making humans more productive and effective. Rather than automating entire jobs, it automates specific tasks within jobs, allowing workers to focus on high-value activities.", ["ai-copilot", "ai-assistant", "human-in-the-loop"], "AI Business"),
    ("ai-transformation", "AI Transformation", "The strategic process of integrating AI throughout an organization's operations and culture.", "AI transformation goes beyond implementing individual AI tools to fundamentally changing how an organization operates. It requires leadership commitment, data infrastructure, and cultural change.", ["ai-strategy", "ai-maturity-model", "ai-readiness"], "AI Business"),
    ("ai-maturity-model", "AI Maturity Model", "Framework for assessing an organization's current AI capabilities and progression toward AI adoption.", "AI maturity models typically range from Level 1 (exploring) to Level 5 (transforming). They assess data infrastructure, talent, governance, and cultural readiness for AI adoption.", ["ai-transformation", "ai-readiness", "ai-strategy"], "AI Business"),
    ("ai-readiness", "AI Readiness", "An organization's preparedness to effectively adopt and benefit from AI technologies.", "AI readiness encompasses data quality, technical infrastructure, talent availability, organizational culture, and strategic alignment. Assessment helps prioritize AI investments.", ["ai-maturity-model", "ai-transformation", "ai-strategy"], "AI Business"),
    ("total-cost-of-ownership", "Total Cost of Ownership (TCO)", "The complete cost of implementing and operating an AI system including development, infrastructure, and maintenance.", "AI TCO includes model API costs, infrastructure, development time, monitoring, retraining, and human oversight. Understanding TCO helps make informed build vs buy decisions.", ["roi-of-ai", "build-vs-buy", "ai-procurement"], "AI Business"),
    ("roi-of-ai", "ROI of AI", "The return on investment from AI implementation measured in cost savings, revenue gains, and productivity.", "AI ROI varies widely by use case. Developer productivity tools show 30-55% improvements. Customer support AI reduces costs 30-50%. Content AI increases output 5-10x.", ["total-cost-of-ownership", "ai-adoption", "ai-strategy"], "AI Business"),
    ("ai-adoption", "AI Adoption", "The process of introducing and integrating AI tools and workflows into an organization.", "Successful AI adoption requires starting with high-impact, low-risk use cases, measuring results, and gradually expanding. Common first steps include AI coding assistants and customer support chatbots.", ["ai-transformation", "ai-readiness", "roi-of-ai"], "AI Business"),
    ("ai-strategy", "AI Strategy", "A plan for how an organization will use AI to achieve business objectives and competitive advantages.", "An AI strategy defines use cases, technology choices, talent needs, governance frameworks, and success metrics. It aligns AI investments with business goals and market opportunities.", ["ai-transformation", "ai-adoption", "ai-maturity-model"], "AI Business"),
    ("build-vs-buy", "Build vs Buy", "The decision between building custom AI solutions or purchasing existing AI products and services.", "The build vs buy decision depends on uniqueness of requirements, available talent, time constraints, and long-term costs. Most organizations benefit from buying for standard use cases and building for competitive differentiators.", ["total-cost-of-ownership", "ai-procurement", "ai-as-a-service"], "AI Business"),
    ("vendor-lock-in", "Vendor Lock-in", "The risk of becoming dependent on a specific AI provider making it costly to switch.", "AI vendor lock-in occurs through proprietary APIs, data formats, and fine-tuned models. Mitigation strategies include using open standards, abstracting provider interfaces, and maintaining data portability.", ["build-vs-buy", "ai-procurement", "ai-as-a-service"], "AI Business"),
    ("ai-procurement", "AI Procurement", "The process of evaluating, selecting, and purchasing AI tools and services for an organization.", "AI procurement should assess model quality, pricing, data privacy, security, integration capabilities, and vendor stability. Proof of concept testing is essential before commitment.", ["build-vs-buy", "vendor-lock-in", "total-cost-of-ownership"], "AI Business"),
    ("ai-compliance", "AI Compliance", "Ensuring AI systems meet regulatory requirements, industry standards, and organizational policies.", "AI compliance covers data privacy (GDPR, CCPA), industry regulations (healthcare, finance), bias auditing, and documentation requirements. The EU AI Act introduces risk-based compliance tiers.", ["ai-governance", "ai-regulation", "responsible-ai"], "AI Business"),

    # Software Engineering (25)
    ("api", "API (Application Programming Interface)", "A set of rules enabling different software systems to communicate and exchange data.", "APIs are the building blocks of modern software, enabling services to share functionality. REST, GraphQL, and gRPC are common API styles. Good API design focuses on simplicity, consistency, and documentation.", ["rest-api", "graphql", "microservices"], "Software Engineering"),
    ("rest-api", "REST API", "An architectural style for APIs using HTTP methods to perform CRUD operations on resources.", "REST APIs use standard HTTP methods (GET, POST, PUT, DELETE) to manipulate resources identified by URLs. They're stateless, cacheable, and the most common API style for web services.", ["api", "graphql", "microservices"], "Software Engineering"),
    ("graphql", "GraphQL", "A query language for APIs that lets clients request exactly the data they need in a single request.", "GraphQL reduces over-fetching and under-fetching of data compared to REST. Clients specify exactly which fields they need. It's ideal for complex applications with multiple data relationships.", ["api", "rest-api", "microservices"], "Software Engineering"),
    ("microservices", "Microservices", "Software architecture where applications are built as small, independent services that communicate via APIs.", "Microservices enable teams to develop, deploy, and scale services independently. Each service handles a specific business capability. They trade simplicity for flexibility and scalability.", ["api", "containerization", "serverless"], "Software Engineering"),
    ("serverless", "Serverless", "Cloud computing model where the provider manages infrastructure and you only pay for actual function execution.", "Serverless functions (AWS Lambda, Vercel Edge Functions) run on-demand without managing servers. They auto-scale and charge per execution, ideal for variable workloads.", ["microservices", "containerization", "infrastructure-as-code"], "Software Engineering"),
    ("containerization", "Containerization", "Packaging applications with their dependencies into portable containers that run consistently anywhere.", "Docker containers ensure applications run identically across development, staging, and production. Kubernetes orchestrates containers at scale for production deployments.", ["microservices", "serverless", "devops"], "Software Engineering"),
    ("ci-cd", "CI/CD (Continuous Integration/Delivery)", "Automated pipelines that build, test, and deploy code changes frequently and reliably.", "CI/CD automates the software delivery pipeline from code commit to production deployment. CI merges and tests code frequently. CD automatically deploys tested code to production.", ["devops", "infrastructure-as-code", "version-control"], "Software Engineering"),
    ("devops", "DevOps", "Practices combining software development and IT operations for faster, more reliable delivery.", "DevOps emphasizes automation, monitoring, collaboration, and continuous improvement. It enables organizations to ship software faster with fewer failures through CI/CD, IaC, and observability.", ["ci-cd", "infrastructure-as-code", "containerization"], "Software Engineering"),
    ("infrastructure-as-code", "Infrastructure as Code (IaC)", "Managing infrastructure through code files rather than manual configuration for reproducibility.", "IaC tools like Terraform, CloudFormation, and Pulumi define infrastructure in version-controlled files. This enables reproducible environments, peer review, and automated provisioning.", ["devops", "ci-cd", "containerization"], "Software Engineering"),
    ("version-control", "Version Control", "System for tracking changes to code over time enabling collaboration and history management.", "Git is the dominant version control system, enabling branching, merging, and collaboration. Platforms like GitHub and GitLab add code review, CI/CD, and project management on top of Git.", ["git", "pull-request", "devops"], "Software Engineering"),
    ("git", "Git", "Distributed version control system for tracking code changes and enabling developer collaboration.", "Git enables developers to work on separate branches, merge changes, and maintain complete project history. It's the foundation of modern software development workflows.", ["version-control", "pull-request", "code-review"], "Software Engineering"),
    ("pull-request", "Pull Request", "A request to merge code changes into a main branch with review and discussion capabilities.", "Pull requests enable code review, discussion, and automated testing before changes are merged. They're central to collaborative development workflows on GitHub and GitLab.", ["git", "code-review", "version-control"], "Software Engineering"),
    ("code-review", "Code Review", "The practice of examining code changes for bugs, style issues, and design problems before merging.", "Code review catches bugs, enforces standards, and shares knowledge across teams. AI tools now assist with automated review while humans focus on design and architecture decisions.", ["pull-request", "git", "technical-debt"], "Software Engineering"),
    ("technical-debt", "Technical Debt", "The cost of shortcuts in code that must eventually be addressed through refactoring.", "Technical debt accumulates when quick solutions are chosen over proper implementations. Managing tech debt requires regular refactoring, code quality metrics, and balanced prioritization.", ["refactoring", "code-review", "agile"], "Software Engineering"),
    ("refactoring", "Refactoring", "Restructuring existing code to improve quality without changing its external behavior.", "Refactoring improves code readability, maintainability, and performance. AI tools can identify refactoring opportunities and even execute safe refactoring patterns automatically.", ["technical-debt", "code-review", "test-driven-development"], "Software Engineering"),
    ("test-driven-development", "Test-Driven Development (TDD)", "Development practice of writing tests before implementation code to guide design.", "TDD follows the red-green-refactor cycle: write a failing test, write code to pass it, then refactor. It produces well-tested, well-designed code and serves as living documentation.", ["refactoring", "agile", "ci-cd"], "Software Engineering"),
    ("agile", "Agile", "Software development methodology emphasizing iterative delivery, collaboration, and adaptation to change.", "Agile frameworks like Scrum and Kanban prioritize working software, customer feedback, and continuous improvement over rigid planning. Most modern software teams use agile practices.", ["scrum", "kanban", "sprint"], "Software Engineering"),
    ("scrum", "Scrum", "Agile framework using fixed-length sprints with defined roles, ceremonies, and artifacts.", "Scrum organizes work into 2-4 week sprints with daily standups, sprint planning, review, and retrospective ceremonies. Roles include Product Owner, Scrum Master, and Development Team.", ["agile", "kanban", "sprint"], "Software Engineering"),
    ("kanban", "Kanban", "Visual workflow management method using boards and cards to track work in progress.", "Kanban limits work in progress, visualizes workflow bottlenecks, and enables continuous delivery without fixed sprints. It's simpler than Scrum and adapts well to maintenance and support work.", ["agile", "scrum", "sprint"], "Software Engineering"),
    ("sprint", "Sprint", "A fixed-length iteration in Scrum during which a team delivers a potentially shippable product increment.", "Sprints typically last 1-4 weeks. They provide predictable delivery cadence, regular stakeholder feedback, and opportunities to inspect and adapt the development process.", ["scrum", "agile", "minimum-viable-product"], "Software Engineering"),
    ("minimum-viable-product", "Minimum Viable Product (MVP)", "The simplest version of a product that validates core assumptions with real users.", "An MVP tests product-market fit with minimal investment. It includes only core features needed to deliver value and collect user feedback. AI tools can help build MVPs in days instead of months.", ["agile", "saas", "sprint"], "Software Engineering"),
    ("saas", "SaaS (Software as a Service)", "Software delivery model where applications are hosted in the cloud and accessed via subscription.", "SaaS products like Slack, Notion, and Figma deliver software through browsers with subscription pricing. The model provides recurring revenue, automatic updates, and lower customer acquisition friction.", ["paas", "iaas", "minimum-viable-product"], "Software Engineering"),
    ("paas", "PaaS (Platform as a Service)", "Cloud platform providing infrastructure and tools for building and deploying applications.", "PaaS providers like Vercel, Railway, and Heroku manage servers, databases, and scaling so developers focus on code. They offer faster deployment at the cost of some infrastructure control.", ["saas", "iaas", "serverless"], "Software Engineering"),
    ("iaas", "IaaS (Infrastructure as a Service)", "Cloud computing providing virtualized computing resources including servers, storage, and networking.", "IaaS providers like AWS, Azure, and GCP offer maximum infrastructure control and flexibility. Organizations manage everything above the hardware layer including OS, runtime, and applications.", ["paas", "saas", "infrastructure-as-code"], "Software Engineering"),
    ("monorepo", "Monorepo", "A version control strategy where multiple projects are stored in a single repository.", "Monorepos simplify code sharing, dependency management, and atomic changes across projects. Tools like Turborepo and Nx optimize builds. Companies like Google and Meta use monorepos at scale.", ["git", "version-control", "ci-cd"], "Software Engineering"),

    # AI Tools & Frameworks (18)
    ("vector-store", "Vector Store", "A storage system optimized for similarity search across high-dimensional embedding vectors.", "Vector stores enable semantic search by finding documents similar in meaning rather than exact keyword matches. They power RAG systems, recommendation engines, and AI search features.", ["vector-database", "embedding", "retrieval-augmented-generation"], "AI Tools"),
    ("model-context-protocol", "Model Context Protocol (MCP)", "An open protocol for connecting AI models to external tools and data sources.", "MCP standardizes how AI assistants access tools, databases, and APIs. It enables AI models to interact with external systems through a common interface, improving interoperability.", ["tool-use", "function-calling", "ai-agent"], "AI Tools"),
    ("agent-to-agent-protocol", "Agent-to-Agent Protocol", "Communication standard enabling AI agents from different systems to collaborate on tasks.", "A2A protocols define how AI agents discover capabilities, delegate tasks, and share results. They enable interoperability between agents built with different frameworks.", ["multi-agent-system", "ai-agent", "orchestration"], "AI Tools"),

    # Marketing & Growth (20)
    ("programmatic-seo", "Programmatic SEO", "Creating large numbers of SEO-optimized pages from templates and data for search engine traffic.", "Programmatic SEO generates hundreds or thousands of targeted pages from data templates. Examples include location pages, comparison pages, and tool directories. It's highly effective for long-tail keywords.", ["search-engine-optimization", "content-marketing", "landing-page"], "Marketing"),
    ("content-marketing", "Content Marketing", "Strategic creation and distribution of valuable content to attract and retain target audiences.", "Content marketing builds trust and authority through blog posts, guides, videos, and podcasts. AI tools have made content production faster while maintaining quality with human editing.", ["search-engine-optimization", "programmatic-seo", "conversion-rate-optimization"], "Marketing"),
    ("search-engine-optimization", "Search Engine Optimization (SEO)", "Practices for improving website visibility in search engine results for target keywords.", "SEO encompasses technical optimization, content creation, and link building. AI tools assist with keyword research, content optimization, and technical auditing to improve search rankings.", ["programmatic-seo", "content-marketing", "landing-page"], "Marketing"),
    ("conversion-rate-optimization", "Conversion Rate Optimization (CRO)", "Systematically improving the percentage of website visitors who complete desired actions.", "CRO uses A/B testing, user research, and analytics to improve conversion. Focus areas include landing pages, signup flows, pricing pages, and checkout experiences.", ["a-b-testing", "funnel-optimization", "landing-page"], "Marketing"),
    ("customer-acquisition-cost", "Customer Acquisition Cost (CAC)", "The total cost of acquiring a new customer including marketing, sales, and onboarding expenses.", "CAC is a critical SaaS metric calculated by dividing total acquisition spend by new customers. Healthy SaaS businesses aim for CAC payback period under 12 months.", ["lifetime-value", "monthly-recurring-revenue", "churn-rate"], "Marketing"),
    ("lifetime-value", "Lifetime Value (LTV)", "The total revenue expected from a customer over their entire relationship with your business.", "LTV helps determine how much to spend on acquisition and which customer segments are most valuable. Healthy SaaS has LTV:CAC ratio of 3:1 or better.", ["customer-acquisition-cost", "churn-rate", "monthly-recurring-revenue"], "Marketing"),
    ("churn-rate", "Churn Rate", "The percentage of customers who cancel or stop using a product within a given time period.", "Churn rate is a critical health metric for subscription businesses. Monthly churn above 5% is concerning for SaaS. AI tools help predict and prevent churn through behavioral analysis.", ["lifetime-value", "customer-acquisition-cost", "monthly-recurring-revenue"], "Marketing"),
    ("monthly-recurring-revenue", "Monthly Recurring Revenue (MRR)", "The predictable revenue a subscription business earns each month from active subscriptions.", "MRR is the core metric for SaaS businesses, tracking growth through new, expansion, contraction, and churned revenue components.", ["annual-recurring-revenue", "churn-rate", "lifetime-value"], "Marketing"),
    ("annual-recurring-revenue", "Annual Recurring Revenue (ARR)", "The annualized value of recurring subscription revenue, typically MRR multiplied by 12.", "ARR is the standard metric for enterprise SaaS valuation. Companies above $1M ARR are considered to have product-market fit in SaaS.", ["monthly-recurring-revenue", "churn-rate", "lifetime-value"], "Marketing"),
    ("net-promoter-score", "Net Promoter Score (NPS)", "Customer loyalty metric measuring how likely customers are to recommend your product.", "NPS ranges from -100 to 100, calculated from survey responses. Scores above 50 are excellent. AI tools can predict NPS from behavioral data without surveys.", ["customer-acquisition-cost", "churn-rate", "conversion-rate-optimization"], "Marketing"),
    ("product-led-growth", "Product-Led Growth (PLG)", "Growth strategy where the product itself drives acquisition, activation, and expansion.", "PLG companies like Slack, Notion, and Figma use free tiers, viral loops, and self-service onboarding to grow. The product experience replaces traditional sales-led acquisition.", ["growth-hacking", "conversion-rate-optimization", "funnel-optimization"], "Marketing"),
    ("growth-hacking", "Growth Hacking", "Rapid experimentation across marketing and product to find the most efficient growth strategies.", "Growth hacking combines data analysis, creative marketing, and product development to drive growth. AI tools enable faster experimentation and more personalized user experiences.", ["product-led-growth", "a-b-testing", "conversion-rate-optimization"], "Marketing"),
    ("a-b-testing", "A/B Testing", "Comparing two versions of a page or feature to determine which performs better statistically.", "A/B testing provides data-driven decisions for optimizing conversion rates. AI can generate test variants, calculate sample sizes, and identify winning combinations faster.", ["conversion-rate-optimization", "funnel-optimization", "growth-hacking"], "Marketing"),
    ("funnel-optimization", "Funnel Optimization", "Improving conversion rates at each stage of the customer journey from awareness to purchase.", "Funnel optimization identifies drop-off points and tests improvements at each stage. AI tools analyze user behavior to pinpoint friction and suggest improvements.", ["conversion-rate-optimization", "a-b-testing", "landing-page"], "Marketing"),
    ("landing-page", "Landing Page", "A standalone web page designed for a specific marketing campaign or conversion goal.", "Effective landing pages focus on a single CTA with compelling copy, social proof, and minimal distractions. AI tools generate and optimize landing page content and layouts.", ["conversion-rate-optimization", "funnel-optimization", "programmatic-seo"], "Marketing"),
    ("call-to-action", "Call to Action (CTA)", "A prompt encouraging users to take a specific action like signing up or purchasing.", "CTAs are critical conversion elements. Effective CTAs use action-oriented language, create urgency, and clearly communicate value. AI tools optimize CTA copy and placement.", ["conversion-rate-optimization", "landing-page", "click-through-rate"], "Marketing"),
    ("click-through-rate", "Click-Through Rate (CTR)", "The percentage of people who click on a link or CTA out of total who see it.", "CTR measures engagement effectiveness for ads, emails, and CTAs. Average email CTR is 2-5%, while Google Ads average 3-5%. AI optimizes elements that improve CTR.", ["call-to-action", "cost-per-click", "conversion-rate-optimization"], "Marketing"),
    ("cost-per-click", "Cost Per Click (CPC)", "The amount paid each time someone clicks on a paid advertisement.", "CPC varies by industry, keyword competitiveness, and platform. Google Ads average CPC ranges from $1-$2 while competitive keywords exceed $50. AI helps optimize bids and reduce CPC.", ["click-through-rate", "return-on-ad-spend", "customer-acquisition-cost"], "Marketing"),
    ("return-on-ad-spend", "Return on Ad Spend (ROAS)", "Revenue generated for every dollar spent on advertising campaigns.", "ROAS of 4:1 or higher is generally considered good. AI optimizes ad targeting, bidding, and creative to maximize ROAS across platforms.", ["cost-per-click", "customer-acquisition-cost", "attribution-modeling"], "Marketing"),
    ("attribution-modeling", "Attribution Modeling", "Methods for assigning credit to marketing touchpoints that contribute to conversions.", "Attribution models range from simple (last-click, first-click) to complex (data-driven, multi-touch). AI-powered attribution provides more accurate credit assignment across the customer journey.", ["return-on-ad-spend", "customer-acquisition-cost", "funnel-optimization"], "Marketing"),
]

def format_term(t):
    slug, term, defn, long_desc, related, cat = t
    related_str = ", ".join(f'"{r}"' for r in related)
    # Escape any quotes in descriptions
    defn = defn.replace('"', '\\"')
    long_desc = long_desc.replace('"', '\\"')
    return (
        f'  {{ slug: "{slug}", term: "{term}", '
        f'definition: "{defn}", '
        f'longDescription: "{long_desc}", '
        f'relatedTerms: [{related_str}], '
        f'category: "{cat}" }},'
    )

lines = ['import type { GlossaryTerm } from "@/types";', '', 'export const glossaryTerms: GlossaryTerm[] = [']
for t in TERMS:
    lines.append(format_term(t))
lines.append('];')
lines.append('')

content = '\n'.join(lines)
with open('/Users/adda247/personal/shipsquad/shipsquad-front/src/data/glossary.ts', 'w') as f:
    f.write(content)

# Validate relatedTerms
slugs = set(t[0] for t in TERMS)
missing = set()
for t in TERMS:
    for r in t[4]:
        if r not in slugs:
            missing.add(r)

print(f"Written {len(TERMS)} glossary terms to glossary.ts ({len(content)} bytes)")
if missing:
    print(f"WARNING: {len(missing)} relatedTerms reference missing slugs: {sorted(missing)}")
else:
    print("All relatedTerms reference valid slugs!")
