#!/usr/bin/env python3
"""Generate cities.ts with 100 cities."""

CITIES = [
    ("san-francisco", "San Francisco", "United States", "North America", "San Francisco is the global epicenter of AI innovation, home to OpenAI, Anthropic, and hundreds of AI startups. ShipSquad AI squads help SF companies ship production software faster.", "870,000", "World's top AI hub with 10,000+ tech companies, Stanford and Berkeley nearby, massive VC ecosystem."),
    ("new-york", "New York", "United States", "North America", "New York's diverse economy drives massive AI adoption across fintech, media, healthcare, and enterprise. ShipSquad squads serve NYC companies building the next generation of AI products.", "8,300,000", "Largest US tech hub by employment, strong fintech and media-tech scenes, growing AI startup ecosystem."),
    ("london", "London", "United Kingdom", "Europe", "London leads European AI adoption with a thriving startup scene and global financial center. ShipSquad helps London companies leverage AI squads for rapid software delivery.", "9,000,000", "Europe's largest tech hub, strong fintech ecosystem, world-class universities, and government AI investment."),
    ("austin", "Austin", "United States", "North America", "Austin's booming tech scene attracts AI companies with lower costs and high quality of life. ShipSquad AI squads help Austin startups scale without building large teams.", "1,000,000", "Fastest-growing US tech hub, major corporate relocations, vibrant startup culture, SXSW innovation."),
    ("seattle", "Seattle", "United States", "North America", "Home to Amazon, Microsoft, and leading AI research labs. ShipSquad helps Seattle companies augment their teams with AI-powered development squads.", "750,000", "Major AI research center, Amazon and Microsoft HQ, strong cloud computing ecosystem."),
    ("toronto", "Toronto", "Canada", "North America", "Toronto is Canada's AI capital with pioneering deep learning research. ShipSquad AI squads help Toronto companies build production software efficiently.", "2,800,000", "Global AI research leader, birthplace of modern deep learning, strong university-industry pipeline."),
    ("berlin", "Berlin", "Germany", "Europe", "Berlin's startup ecosystem thrives with AI innovation across manufacturing, mobility, and enterprise. ShipSquad squads help Berlin companies ship faster with AI-powered development.", "3,700,000", "Europe's startup capital, strong engineering talent, affordable compared to London, growing AI scene."),
    ("singapore", "Singapore", "Singapore", "Asia", "Singapore is Southeast Asia's AI hub with strong government support and enterprise adoption. ShipSquad AI squads serve Singapore businesses building AI-powered solutions.", "5,900,000", "Asia's top business hub, Smart Nation initiative, strong AI policy framework, gateway to ASEAN market."),
    ("tel-aviv", "Tel Aviv", "Israel", "Middle East", "Tel Aviv's innovation ecosystem produces more startups per capita than anywhere. ShipSquad AI squads help Israeli companies move fast from idea to production.", "460,000", "Startup Nation capital, highest VC per capita globally, strong cybersecurity and AI sectors."),
    ("bangalore", "Bangalore", "India", "Asia", "India's Silicon Valley and AI capital with massive engineering talent. ShipSquad helps Bangalore companies augment teams with AI-powered development squads.", "12,800,000", "India's top tech hub, massive IT services industry, growing AI startup ecosystem, abundant engineering talent."),
    ("tokyo", "Tokyo", "Japan", "Asia", "Tokyo drives AI adoption in robotics, manufacturing, and enterprise. ShipSquad AI squads help Tokyo companies modernize with cutting-edge software development.", "14,000,000", "World's largest metro economy, strong robotics and manufacturing AI, corporate innovation programs."),
    ("paris", "Paris", "France", "Europe", "Paris is emerging as Europe's AI powerhouse with Mistral and strong government investment. ShipSquad squads help Parisian companies build AI-powered products.", "2,200,000", "Growing AI hub with Mistral AI, strong math and engineering tradition, Station F startup campus."),
    ("los-angeles", "Los Angeles", "United States", "North America", "LA's entertainment, gaming, and creator economy drives unique AI adoption. ShipSquad AI squads help LA companies build creative technology products.", "4,000,000", "Entertainment and creator economy hub, growing AI scene, strong gaming and media-tech industry."),
    ("boston", "Boston", "United States", "North America", "Boston's world-class universities fuel AI research and biotech innovation. ShipSquad AI squads help Boston companies bridge research and production software.", "700,000", "MIT and Harvard ecosystem, strong biotech-AI intersection, deep research talent pipeline."),
    ("dubai", "Dubai", "UAE", "Middle East", "Dubai's ambitious AI strategy drives enterprise adoption across government and private sectors. ShipSquad AI squads help Dubai companies build world-class software.", "3,500,000", "Ambitious AI strategy, government digital transformation, growing startup ecosystem, tax-free environment."),
    ("amsterdam", "Amsterdam", "Netherlands", "Europe", "Amsterdam's progressive tech scene and international talent pool drive AI innovation. ShipSquad helps Amsterdam companies ship software faster.", "900,000", "Strong international tech community, progressive business environment, growing AI and data science scene."),
    ("sydney", "Sydney", "Australia", "Oceania", "Sydney leads Australia's AI adoption across fintech, mining, and enterprise. ShipSquad AI squads help Australian companies build production-ready software.", "5,400,000", "Australia's tech capital, strong fintech scene, growing AI adoption, Atlassian headquarters."),
    ("denver", "Denver", "United States", "North America", "Denver's growing tech scene offers AI innovation with mountain lifestyle appeal. ShipSquad squads help Denver companies build without large local teams.", "750,000", "Fast-growing tech hub, aerospace and defense AI, lower cost than coastal cities, strong quality of life."),
    ("miami", "Miami", "United States", "North America", "Miami's emerging tech scene attracts AI companies with crypto, fintech, and Latin American connections. ShipSquad helps Miami companies scale with AI squads.", "450,000", "Emerging tech hub, strong crypto and fintech scene, gateway to Latin America, growing startup ecosystem."),
    ("chicago", "Chicago", "United States", "North America", "Chicago's enterprise market drives AI adoption across finance, logistics, and manufacturing. ShipSquad AI squads help Midwest companies modernize.", "2,700,000", "Strong enterprise market, major financial center, growing startup scene, world-class universities."),
    ("vancouver", "Vancouver", "Canada", "North America", "Vancouver's AI and gaming industries thrive with international talent. ShipSquad squads help Vancouver companies build production software efficiently.", "2,600,000", "Strong AI and gaming industry, international talent pool, growing startup ecosystem, beautiful location."),
    ("stockholm", "Stockholm", "Sweden", "Europe", "Stockholm produces more unicorns per capita than almost anywhere. ShipSquad AI squads help Swedish companies maintain their innovation edge.", "1,000,000", "Unicorn factory of Europe, Spotify and Klarna home, strong engineering culture, progressive innovation."),
    ("mumbai", "Mumbai", "India", "Asia", "Mumbai's financial center drives AI adoption in banking, insurance, and enterprise. ShipSquad helps Mumbai companies build AI-powered fintech solutions.", "21,000,000", "India's financial capital, massive enterprise market, growing fintech AI adoption, strong talent pool."),
    ("shenzhen", "Shenzhen", "China", "Asia", "Shenzhen leads hardware-AI integration with the world's largest electronics manufacturing ecosystem. ShipSquad AI squads bridge hardware and software development.", "17,600,000", "Hardware innovation capital, massive electronics manufacturing, strong AI chip development, Huawei and Tencent HQ."),
    ("seoul", "Seoul", "South Korea", "Asia", "Seoul drives AI innovation in semiconductors, gaming, and consumer tech. ShipSquad AI squads help Korean companies build AI-powered products.", "10,000,000", "Leading semiconductor hub, strong gaming and consumer tech, Samsung and LG AI research, government AI investment."),
    ("zurich", "Zurich", "Switzerland", "Europe", "Zurich combines banking precision with AI innovation through ETH Zurich research. ShipSquad helps Swiss companies build reliable AI-powered software.", "435,000", "Strong fintech and AI research, ETH Zurich, Google's largest European engineering office, precision engineering culture."),
    ("dublin", "Dublin", "Ireland", "Europe", "Dublin hosts European HQs of major tech companies with growing AI adoption. ShipSquad AI squads help Dublin companies build and scale faster.", "1,400,000", "European tech hub with Google, Meta, and Microsoft EU headquarters, strong talent pipeline, favorable tax environment."),
    ("melbourne", "Melbourne", "Australia", "Oceania", "Melbourne's diverse economy drives AI adoption in education, healthcare, and creative industries. ShipSquad helps Melbourne companies build innovative software.", "5,100,000", "Australia's second tech hub, strong university research, creative industries, growing startup scene."),
    ("helsinki", "Helsinki", "Finland", "Europe", "Helsinki's AI leadership includes the global Elements of AI course and strong startup culture. ShipSquad AI squads help Finnish companies innovate.", "660,000", "Global AI education leader, Nokia legacy talent, strong startup ecosystem, government AI strategy."),
    ("barcelona", "Barcelona", "Spain", "Europe", "Barcelona's tech scene combines Mediterranean lifestyle with growing AI innovation. ShipSquad helps Barcelona companies build production software.", "1,600,000", "Growing tech hub, Mobile World Congress host, strong international community, emerging AI startup scene."),
    ("washington-dc", "Washington D.C.", "United States", "North America", "DC drives AI adoption in government, defense, and policy. ShipSquad AI squads help DC companies navigate complex government technology requirements.", "700,000", "Government tech market, defense AI, strong cybersecurity sector, growing commercial tech scene."),
    ("portland", "Portland", "United States", "North America", "Portland's creative tech scene drives AI adoption in design, sustainability, and commerce. ShipSquad AI squads help Portland companies build innovative products.", "650,000", "Creative tech culture, strong sustainability focus, growing startup scene, lower cost than SF."),
    ("atlanta", "Atlanta", "United States", "North America", "Atlanta's diverse economy drives AI adoption in fintech, logistics, and healthcare. ShipSquad AI squads help Atlanta companies modernize.", "500,000", "Growing tech hub, strong fintech and healthcare, major logistics center, diverse talent pool."),
    ("montreal", "Montreal", "Canada", "North America", "Montreal is a global AI research capital with Mila and Yoshua Bengio's deep learning lab. ShipSquad AI squads help Montreal companies productionize research.", "1,800,000", "World-class AI research with Mila, strong gaming industry, bilingual talent pool, affordable living."),
    ("munich", "Munich", "Germany", "Europe", "Munich's automotive and enterprise AI drives innovation in manufacturing and mobility. ShipSquad AI squads help Munich companies build intelligent systems.", "1,500,000", "Strong automotive AI, BMW and Siemens HQ, technical university talent, enterprise innovation."),
    ("hong-kong", "Hong Kong", "China", "Asia", "Hong Kong bridges Chinese and global AI markets with strong finance and enterprise adoption. ShipSquad helps Hong Kong companies build cross-market solutions.", "7,500,000", "Global financial center, gateway between China and world markets, growing tech startup ecosystem."),
    ("delhi", "Delhi", "India", "Asia", "Delhi NCR's massive market drives AI adoption across government, retail, and enterprise. ShipSquad AI squads help Delhi companies scale technology.", "32,000,000", "India's capital region, massive government and enterprise market, growing startup ecosystem, IIT talent."),
    ("lisbon", "Lisbon", "Portugal", "Europe", "Lisbon attracts global tech talent with Web Summit and digital nomad-friendly policies. ShipSquad AI squads help Lisbon companies compete globally.", "550,000", "Web Summit home, growing startup ecosystem, digital nomad hub, attractive tax regime for tech workers."),
    ("cairo", "Cairo", "Egypt", "Africa", "Cairo leads Middle East and African AI adoption with a growing tech ecosystem. ShipSquad AI squads help Egyptian companies build world-class software.", "10,000,000", "Largest city in Middle East/Africa, growing tech startup scene, strong engineering education, regional hub."),
    ("nairobi", "Nairobi", "Kenya", "Africa", "Nairobi's Silicon Savannah drives AI innovation across mobile payments, agriculture, and fintech. ShipSquad AI squads help Kenyan companies build scalable solutions.", "4,700,000", "Africa's tech capital, M-Pesa innovation, growing AI startup ecosystem, strong mobile-first market."),
    ("lagos", "Lagos", "Nigeria", "Africa", "Lagos drives Africa's largest tech ecosystem with AI adoption in fintech and commerce. ShipSquad helps Nigerian companies build production-grade software.", "16,000,000", "Africa's largest tech market, booming fintech scene, Flutterwave and Paystack success stories."),
    ("cape-town", "Cape Town", "South Africa", "Africa", "Cape Town's tech scene combines innovation with access to African markets. ShipSquad AI squads help South African companies scale regionally.", "4,800,000", "Growing tech hub, strong international community, gateway to African markets, emerging AI scene."),
    ("sao-paulo", "São Paulo", "Brazil", "South America", "São Paulo is Latin America's tech capital with massive AI adoption in fintech and enterprise. ShipSquad AI squads help Brazilian companies compete globally.", "12,300,000", "Latin America's largest tech market, strong fintech ecosystem, massive enterprise opportunity, Nubank success story."),
    ("mexico-city", "Mexico City", "Mexico", "North America", "Mexico City's growing tech scene drives AI adoption in fintech, logistics, and enterprise. ShipSquad AI squads help Mexican companies innovate.", "9,200,000", "Growing tech hub, nearshore talent, strong engineering education, emerging AI startup scene."),
    ("buenos-aires", "Buenos Aires", "Argentina", "South America", "Buenos Aires produces world-class engineering talent with growing AI startup adoption. ShipSquad AI squads help Argentine companies build global products.", "3,100,000", "Strong engineering talent, growing startup ecosystem, Mercado Libre success story, affordable talent."),
    ("bogota", "Bogotá", "Colombia", "South America", "Bogotá's tech ecosystem is growing rapidly with AI adoption in fintech and government. ShipSquad AI squads help Colombian companies modernize.", "7,400,000", "Growing tech scene, strong nearshore talent, government digital transformation, emerging AI adoption."),
    ("taipei", "Taipei", "Taiwan", "Asia", "Taipei leads semiconductor innovation powering global AI with TSMC and strong hardware ecosystem. ShipSquad AI squads help Taiwanese companies build AI software.", "2,600,000", "Semiconductor capital, TSMC home, strong hardware-software integration, growing AI startup scene."),
    ("jakarta", "Jakarta", "Indonesia", "Asia", "Jakarta drives Southeast Asia's largest digital economy with massive AI adoption opportunity. ShipSquad helps Indonesian companies build AI-powered products.", "11,000,000", "Largest Southeast Asian economy, growing digital ecosystem, GoTo and Tokopedia success, massive market."),
    ("bangkok", "Bangkok", "Thailand", "Asia", "Bangkok's digital economy drives AI adoption in tourism, fintech, and commerce. ShipSquad AI squads help Thai companies compete in the digital age.", "10,500,000", "Growing digital economy, strong tourism tech, emerging fintech scene, regional connectivity."),
    ("kuala-lumpur", "Kuala Lumpur", "Malaysia", "Asia", "KL's digital economy and government AI programs drive adoption across sectors. ShipSquad AI squads help Malaysian companies build innovative solutions.", "8,000,000", "Growing tech hub, strong government digital programs, strategic Southeast Asian location, affordable talent."),
    ("riyadh", "Riyadh", "Saudi Arabia", "Middle East", "Riyadh's Vision 2030 drives massive AI investment and digital transformation. ShipSquad AI squads help Saudi companies build next-generation software.", "7,700,000", "Vision 2030 massive tech investment, NEOM smart city project, growing AI ecosystem, government backing."),
    ("philadelphia", "Philadelphia", "United States", "North America", "Philadelphia's healthcare and education sectors drive unique AI adoption opportunities. ShipSquad AI squads help Philly companies innovate.", "1,600,000", "Strong healthcare and education sectors, growing tech scene, affordable compared to NYC, Ivy League talent."),
    ("dallas", "Dallas", "United States", "North America", "Dallas-Fort Worth's enterprise market drives AI adoption in telecom, logistics, and finance. ShipSquad AI squads help DFW companies modernize.", "1,300,000", "Large enterprise market, strong telecom and finance sectors, growing tech scene, business-friendly environment."),
    ("phoenix", "Phoenix", "United States", "North America", "Phoenix's fast-growing tech scene attracts AI companies with lower costs and semiconductor manufacturing. ShipSquad helps Phoenix companies scale.", "1,600,000", "Fast-growing tech hub, semiconductor manufacturing, lower cost of living, Intel and TSMC investments."),
    ("san-diego", "San Diego", "United States", "North America", "San Diego's biotech and defense sectors drive specialized AI adoption. ShipSquad AI squads help SD companies build domain-specific AI products.", "1,400,000", "Strong biotech and defense tech, Qualcomm HQ, UC San Diego research, growing startup ecosystem."),
    ("raleigh", "Raleigh", "United States", "North America", "Research Triangle's university ecosystem drives AI innovation in biotech and enterprise. ShipSquad AI squads help Triangle companies scale.", "470,000", "Research Triangle Park, Duke/UNC/NC State ecosystem, growing tech hub, strong life sciences AI."),
    ("nashville", "Nashville", "United States", "North America", "Nashville's healthcare industry drives unique AI adoption in health-tech and enterprise. ShipSquad AI squads help Nashville companies innovate.", "690,000", "Healthcare capital of the US, growing tech scene, strong music-tech intersection, affordable living."),
    ("pittsburgh", "Pittsburgh", "United States", "North America", "Pittsburgh's AI leadership through CMU drives robotics and autonomous systems innovation. ShipSquad AI squads help Pittsburgh companies productionize research.", "300,000", "Carnegie Mellon AI research, strong robotics scene, autonomous vehicle development, Duolingo HQ."),
    ("oslo", "Oslo", "Norway", "Europe", "Oslo's maritime, energy, and fintech sectors drive specialized AI adoption. ShipSquad AI squads help Norwegian companies build intelligent solutions.", "700,000", "Strong maritime and energy AI, wealthy market for innovation, growing startup scene, high quality of life."),
    ("copenhagen", "Copenhagen", "Denmark", "Europe", "Copenhagen's green tech and design-driven culture creates unique AI opportunities. ShipSquad AI squads help Danish companies build sustainable solutions.", "800,000", "Strong green-tech and sustainability focus, design-driven innovation, growing AI startup scene."),
    ("warsaw", "Warsaw", "Poland", "Europe", "Warsaw's growing tech scene offers strong engineering talent for AI development. ShipSquad AI squads help Polish companies build world-class products.", "1,800,000", "Strong engineering talent, competitive costs, growing startup ecosystem, CD Projekt and Allegro success."),
    ("prague", "Prague", "Czech Republic", "Europe", "Prague's engineering tradition drives AI adoption across enterprise and cybersecurity. ShipSquad AI squads help Czech companies compete globally.", "1,300,000", "Strong engineering tradition, affordable tech talent, growing startup scene, central European hub."),
    ("bucharest", "Bucharest", "Romania", "Europe", "Bucharest's deep tech talent pool drives AI development at competitive costs. ShipSquad AI squads help Romanian companies build global products.", "2,200,000", "Strong tech talent, UiPath unicorn success, affordable development, growing AI and automation scene."),
    ("vienna", "Vienna", "Austria", "Europe", "Vienna's innovation focus drives AI adoption across manufacturing, finance, and government. ShipSquad AI squads help Austrian companies modernize.", "1,900,000", "High quality of life, strong manufacturing sector, growing tech scene, central European connectivity."),
    ("brussels", "Brussels", "Belgium", "Europe", "Brussels' EU hub status drives AI policy and enterprise adoption. ShipSquad AI squads help Belgian companies navigate EU AI regulations.", "1,200,000", "EU institutional hub, AI policy center, strong enterprise market, international business environment."),
    ("milan", "Milan", "Italy", "Europe", "Milan's fashion, finance, and manufacturing drive unique AI adoption opportunities. ShipSquad AI squads help Italian companies digitize.", "1,400,000", "Fashion and design AI, strong manufacturing sector, growing tech scene, financial center of Italy."),
    ("madrid", "Madrid", "Spain", "Europe", "Madrid's growing tech scene drives AI adoption in telecom, finance, and enterprise. ShipSquad AI squads help Spanish companies innovate.", "3,300,000", "Growing tech hub, strong telecom sector, Telefonica innovation, emerging startup ecosystem."),
    ("edinburgh", "Edinburgh", "United Kingdom", "Europe", "Edinburgh's AI research through the University drives innovation in fintech and data. ShipSquad AI squads help Scottish companies build cutting-edge products.", "540,000", "Strong AI research university, growing fintech scene, Edinburgh Futures Institute, Skyscanner HQ."),
    ("manchester", "Manchester", "United Kingdom", "Europe", "Manchester's tech scene is the UK's fastest-growing with strong AI adoption. ShipSquad AI squads help Manchester companies scale.", "550,000", "UK's fastest-growing tech city, strong BBC and media-tech, affordable compared to London, diverse talent."),
    ("hyderabad", "Hyderabad", "India", "Asia", "Hyderabad's HITEC City drives AI adoption in enterprise IT and pharmaceuticals. ShipSquad AI squads help Hyderabad companies build intelligent products.", "10,000,000", "Major IT hub, Microsoft and Google offices, strong pharma-tech, affordable talent, growing AI ecosystem."),
    ("pune", "Pune", "India", "Asia", "Pune's engineering colleges and IT parks drive AI adoption and innovation. ShipSquad AI squads help Pune companies build production-grade software.", "7,400,000", "Strong engineering education, growing IT hub, affordable talent, proximity to Mumbai, emerging AI scene."),
    ("ho-chi-minh-city", "Ho Chi Minh City", "Vietnam", "Asia", "HCMC's fast-growing digital economy drives AI adoption in fintech and manufacturing. ShipSquad AI squads help Vietnamese companies innovate.", "9,000,000", "Fast-growing digital economy, strong manufacturing base, young tech talent, emerging startup ecosystem."),
    ("manila", "Manila", "Philippines", "Asia", "Manila's BPO industry transforms into AI-powered services. ShipSquad AI squads help Philippine companies build intelligent automation.", "14,000,000", "Major BPO industry transitioning to AI, young tech-savvy population, growing startup scene."),
    ("colombo", "Colombo", "Sri Lanka", "Asia", "Colombo's growing tech scene drives AI adoption in tourism and enterprise. ShipSquad AI squads help Sri Lankan companies build global products.", "750,000", "Growing tech outsourcing hub, strong engineering talent, emerging startup ecosystem, strategic location."),
    ("istanbul", "Istanbul", "Turkey", "Europe", "Istanbul bridges European and Asian tech markets with growing AI startup activity. ShipSquad AI squads help Turkish companies scale.", "15,500,000", "Bridges Europe and Asia, strong engineering talent, growing tech ecosystem, Trendyol and Peak Games success."),
    ("doha", "Doha", "Qatar", "Middle East", "Qatar's AI investment drives innovation in energy, sports technology, and smart city development. ShipSquad AI squads help Qatari companies build solutions.", "2,400,000", "Strong AI investment, smart city projects, Qatar Computing Research Institute, wealthy innovation market."),
    ("bengaluru-electronic-city", "Bengaluru Electronic City", "India", "Asia", "Electronic City is India's premier IT hub housing AI labs for Infosys, Wipro, and global tech firms. ShipSquad AI squads serve this concentrated tech corridor.", "1,200,000", "India's IT corridor, major tech campuses, strong AI research, concentrated engineering talent."),
    ("tallinn", "Tallinn", "Estonia", "Europe", "Tallinn leads digital government innovation with e-Residency and growing AI adoption. ShipSquad AI squads help Estonian companies build digital-first products.", "450,000", "World's most digital government, e-Residency program, Wise and Bolt unicorns, strong startup ecosystem."),
    ("kigali", "Kigali", "Rwanda", "Africa", "Kigali drives Africa's AI adoption with government support and emerging tech hub status. ShipSquad AI squads help Rwandan companies build innovative solutions.", "1,700,000", "Strong government tech support, Carnegie Mellon Africa campus, growing tech hub, drone delivery innovation."),
    ("accra", "Accra", "Ghana", "Africa", "Accra's growing tech scene makes it West Africa's emerging AI hub. ShipSquad AI squads help Ghanaian companies build scalable technology.", "4,000,000", "Growing tech hub, Google AI center, strong English-speaking talent, emerging startup ecosystem."),
    ("lima", "Lima", "Peru", "South America", "Lima's growing digital economy drives AI adoption in mining, agriculture, and fintech. ShipSquad AI squads help Peruvian companies modernize.", "10,000,000", "Growing digital economy, strong mining and agriculture tech, emerging fintech scene."),
    ("santiago", "Santiago", "Chile", "South America", "Santiago leads South American AI innovation with strong startup support programs. ShipSquad AI squads help Chilean companies compete globally.", "6,300,000", "Most developed South American tech ecosystem, Start-Up Chile program, strong engineering education."),
    ("medellín", "Medellín", "Colombia", "South America", "Medellín transformed from industrial city to innovation hub with growing AI adoption. ShipSquad AI squads help Medellín companies build global products.", "2,500,000", "Remarkable tech transformation, growing innovation district, strong engineering talent, Ruta N tech hub."),
    ("abuja", "Abuja", "Nigeria", "Africa", "Abuja's government and enterprise market drives AI adoption in public services. ShipSquad AI squads help Nigerian government-tech companies innovate.", "3,600,000", "Nigeria's capital, growing government tech, enterprise AI adoption, emerging startup scene."),
    ("san-jose", "San Jose", "United States", "North America", "The capital of Silicon Valley, home to major tech HQs driving AI innovation. ShipSquad AI squads serve the heart of the global tech industry.", "1,000,000", "Silicon Valley capital, Apple and Google nearby, highest concentration of tech workers, massive VC ecosystem."),
    ("minneapolis", "Minneapolis", "United States", "North America", "Minneapolis drives AI adoption in healthcare, retail, and agriculture technology. ShipSquad AI squads help Minnesota companies innovate.", "425,000", "Strong healthcare and retail tech, Target and UnitedHealth, growing startup scene, affordable living."),
    ("salt-lake-city", "Salt Lake City", "United States", "North America", "Silicon Slopes drives Utah's AI and SaaS innovation with rapid tech growth. ShipSquad AI squads help Utah companies scale.", "200,000", "Silicon Slopes tech hub, strong SaaS ecosystem, Qualtrics and Domo, affordable with high growth."),
    ("charlotte", "Charlotte", "United States", "North America", "Charlotte's banking sector drives AI adoption in fintech and financial services. ShipSquad AI squads help NC companies build innovative fintech.", "900,000", "US banking capital, strong fintech scene, Bank of America innovation, growing tech ecosystem."),
    ("detroit", "Detroit", "United States", "North America", "Detroit's automotive industry drives AI adoption in autonomous vehicles and manufacturing. ShipSquad AI squads help Michigan companies build intelligent systems.", "640,000", "Autonomous vehicle capital, strong automotive AI, GM and Ford innovation labs, affordable renaissance."),
    ("auckland", "Auckland", "New Zealand", "Oceania", "Auckland drives New Zealand's growing tech sector with AI adoption across agriculture and SaaS. ShipSquad AI squads help Kiwi companies compete globally.", "1,700,000", "New Zealand's tech capital, strong SaaS scene, growing AI adoption, gateway to Asia-Pacific markets."),
    ("bengaluru-whitefield", "Bengaluru Whitefield", "India", "Asia", "Whitefield is one of India's largest IT corridors with major AI and enterprise tech development. ShipSquad AI squads serve this growing tech district.", "800,000", "Major IT corridor, SAP Labs and global tech offices, strong AI engineering talent, growing startup scene."),
    ("guadalajara", "Guadalajara", "Mexico", "North America", "Mexico's Silicon Valley drives AI adoption with strong engineering talent and nearshore advantages. ShipSquad AI squads help GDL companies build global products.", "1,500,000", "Mexico's Silicon Valley, Intel and Oracle offices, strong engineering education, nearshore hub."),
    ("kiev", "Kyiv", "Ukraine", "Europe", "Kyiv's resilient tech scene produces world-class engineering talent and AI innovation. ShipSquad AI squads help Ukrainian companies build global products.", "3,000,000", "Strong engineering talent, competitive costs, resilient tech ecosystem, Grammarly and GitLab roots."),
    ("dhaka", "Dhaka", "Bangladesh", "Asia", "Dhaka's growing IT sector drives AI adoption in garment manufacturing and fintech. ShipSquad AI squads help Bangladeshi companies modernize.", "22,000,000", "Growing IT outsourcing, strong garment-tech innovation, large young population, emerging startup ecosystem."),
    ("hanoi", "Hanoi", "Vietnam", "Asia", "Hanoi's tech scene complements HCMC with growing AI adoption in government and enterprise. ShipSquad AI squads help Vietnamese companies innovate.", "8,000,000", "Growing tech hub, strong engineering education, government digital transformation, emerging AI scene."),
    ("johannesburg", "Johannesburg", "South Africa", "Africa", "Johannesburg drives South Africa's fintech and enterprise AI adoption. ShipSquad AI squads help SA companies build innovative technology.", "6,000,000", "South Africa's business capital, strong fintech scene, growing enterprise AI adoption, diverse talent."),
    ("dar-es-salaam", "Dar es Salaam", "Tanzania", "Africa", "East Africa's commercial hub with growing digital economy and AI adoption. ShipSquad AI squads help Tanzanian companies build digital solutions.", "7,400,000", "East Africa's commercial hub, growing mobile money ecosystem, emerging tech startup scene."),
    ("porto", "Porto", "Portugal", "Europe", "Porto's growing tech scene complements Lisbon with strong engineering talent and lower costs. ShipSquad AI squads help Porto companies build world-class software products.", "1,300,000", "Growing tech hub, strong university engineering programs, Web Summit expansion, affordable compared to Lisbon, thriving startup community."),
    ("vilnius", "Vilnius", "Lithuania", "Europe", "Vilnius is a rising Baltic tech hub with strong fintech innovation and AI adoption. ShipSquad AI squads help Lithuanian companies compete globally.", "580,000", "Strong fintech sector with Revolut and Vinted roots, EU digital innovation hub, competitive talent costs, growing AI startup scene."),
    ("bratislava", "Bratislava", "Slovakia", "Europe", "Bratislava's central European location and engineering talent drive AI adoption across automotive and enterprise. ShipSquad AI squads help Slovak companies modernize.", "475,000", "Central European tech hub, strong automotive and manufacturing AI, competitive engineering talent, growing startup ecosystem, EU connectivity."),
]

def format_city(c):
    slug, name, country, region, desc, pop, tech = c
    return (
        f'  {{ slug: "{slug}", name: "{name}", country: "{country}", '
        f'region: "{region}", description: "{desc}", '
        f'population: "{pop}", techScene: "{tech}" }},'
    )

lines = ['import type { City } from "@/types";', '', 'export const cities: City[] = [']
for c in CITIES:
    lines.append(format_city(c))
lines.append('];')
lines.append('')

content = '\n'.join(lines)
with open('/Users/adda247/personal/shipsquad/shipsquad-front/src/data/cities.ts', 'w') as f:
    f.write(content)
print(f"Written {len(CITIES)} cities to cities.ts ({len(content)} bytes)")
