#!/usr/bin/env python3
"""Generate tools.ts data file with 150 AI tool entries."""

TOOLS = [
    # [slug, name, category, description, pricing, pricingDetail, features, pros, cons, url, alt, priceP, reviewP, rating]
    # AI Chatbots
    ("chatgpt", "ChatGPT", "AI Chatbot", "OpenAI's conversational AI assistant powered by GPT-4 and GPT-4o for text, image, and code generation.", "Freemium", "Free tier available, Plus at $20/mo, Team at $25/user/mo, Enterprise custom pricing", ["Natural language conversation", "Code generation and debugging", "Image analysis and generation", "Custom GPTs and plugin ecosystem", "Web browsing and data analysis"], ["Easy to use with intuitive interface", "Massive plugin and GPT ecosystem", "Strong reasoning and creative writing", "Regular model updates"], ["Can hallucinate confidently", "Usage limits on free tier", "Privacy concerns with data training"], "https://chat.openai.com", True, True, True, 4.7, ["claude", "gemini", "perplexity"]),
    ("claude", "Claude", "AI Chatbot", "Anthropic's AI assistant known for nuanced reasoning, safety, and exceptional coding and analysis capabilities.", "Freemium", "Free tier, Pro at $20/mo, Team at $25/user/mo, Enterprise custom", ["Advanced reasoning and analysis", "200K token context window", "Code generation and review", "Artifacts for interactive content", "Vision and document analysis"], ["Superior reasoning and nuance", "Excellent at coding tasks", "Large context window for long documents", "Strong safety and honesty"], ["Smaller plugin ecosystem than ChatGPT", "Limited web browsing", "Rate limits on free tier"], "https://claude.ai", True, True, True, 4.8, ["chatgpt", "gemini", "perplexity"]),
    ("gemini", "Gemini", "AI Chatbot", "Google's multimodal AI model with deep integration into Google Workspace and Search.", "Freemium", "Free tier, Advanced at $19.99/mo included with Google One AI Premium", ["Multimodal understanding", "Google Workspace integration", "1M token context window", "Real-time information access", "Code generation with Gemini Code Assist"], ["Deep Google ecosystem integration", "Massive context window", "Strong multimodal capabilities", "Free tier is generous"], ["Can be inconsistent in quality", "Less refined than competitors for coding", "Limited third-party integrations"], "https://gemini.google.com", True, True, True, 4.5, ["chatgpt", "claude", "perplexity"]),
    ("perplexity", "Perplexity", "AI Search", "AI-powered search engine that provides cited, real-time answers by combining LLMs with web search.", "Freemium", "Free tier, Pro at $20/mo with unlimited Pro searches", ["Real-time web search with citations", "Multiple AI model selection", "Focus modes for different search types", "Collections for organizing research", "API access for developers"], ["Excellent source citations", "Real-time information access", "Clean and focused interface", "Multiple model options"], ["Limited creative writing ability", "Pro searches have daily limits", "Less conversational than ChatGPT"], "https://perplexity.ai", True, True, True, 4.6, ["chatgpt", "claude", "you-com"]),
    ("copilot", "Microsoft Copilot", "AI Chatbot", "Microsoft's AI assistant integrated across Windows, Edge, and Microsoft 365 productivity suite.", "Freemium", "Free tier, Copilot Pro at $20/mo, Microsoft 365 Copilot at $30/user/mo", ["Microsoft 365 integration", "Windows and Edge built-in", "Image generation with DALL-E", "Enterprise data protection", "Plugin and connector ecosystem"], ["Deep Microsoft ecosystem integration", "Free access in Windows and Edge", "Strong enterprise compliance"], ["Less capable than ChatGPT for coding", "Best features require M365 subscription", "Can feel slow compared to competitors"], "https://copilot.microsoft.com", True, True, True, 4.3, ["chatgpt", "claude", "gemini"]),
    ("llama", "Meta Llama", "AI Chatbot", "Meta's open-source large language model family available for self-hosting and customization.", "Open Source", "Free to use, hosting costs vary by provider", ["Open-source weights and code", "Multiple model sizes available", "Fine-tuning support", "Self-hosted deployment options", "Commercial use license"], ["Completely free and open-source", "Full control over deployment", "Strong community and ecosystem", "No data sent to third parties"], ["Requires technical setup", "No official hosted chat interface", "Lags behind proprietary models"], "https://llama.meta.com", True, True, True, 4.4, ["mistral", "deepseek", "chatgpt"]),
    ("deepseek", "DeepSeek", "AI Chatbot", "Chinese AI lab's frontier model offering strong reasoning capabilities at significantly lower cost.", "Freemium", "Free tier, API pricing at fraction of GPT-4 cost", ["Advanced reasoning and math", "Code generation", "128K context window", "Open-source model weights", "Extremely low API pricing"], ["Exceptional value for money", "Strong reasoning capabilities", "Open-source availability", "Competitive with frontier models"], ["Based in China raises data concerns", "Less polished interface", "Smaller ecosystem"], "https://chat.deepseek.com", True, True, True, 4.5, ["chatgpt", "claude", "llama"]),
    ("gpt-5", "GPT-5", "AI Chatbot", "OpenAI's next-generation AI model pushing the boundaries of multimodal AI and complex reasoning.", "Paid", "Available through ChatGPT Plus and API, pricing TBD", ["Advanced multimodal reasoning", "Improved code generation", "Enhanced creative capabilities", "Better factual accuracy", "Extended context understanding"], ["Cutting-edge AI capabilities", "Strong multimodal features", "Improved accuracy over GPT-4"], ["Premium pricing expected", "May require Plus subscription", "High API costs"], "https://openai.com", False, True, True, 4.8, ["claude-opus-4", "gemini-3", "deepseek-v4"]),
    ("claude-opus-4", "Claude Opus 4", "AI Chatbot", "Anthropic's most capable model setting new standards in reasoning depth and code generation quality.", "Paid", "Available through Claude Pro and API", ["Frontier reasoning capabilities", "Superior code generation", "Extended thinking mode", "Tool use and agentic workflows", "200K context window"], ["Best-in-class reasoning", "Exceptional coding ability", "Strong safety features"], ["Premium pricing", "Slower than smaller models", "Rate limited on Pro plan"], "https://claude.ai", False, True, True, 4.9, ["gpt-5", "gemini-3", "deepseek-v4"]),
    ("gemini-3", "Gemini 3", "AI Chatbot", "Google's frontier AI model with superior multimodal understanding and deep search integration.", "Paid", "Included with Google AI Premium, API pricing varies", ["Frontier multimodal AI", "Native Google Search integration", "Massive context window", "Advanced code capabilities", "Real-time information"], ["Superior multimodal features", "Google ecosystem integration", "Competitive pricing"], ["Availability may be limited", "Google dependency", "Less tested than predecessors"], "https://gemini.google.com", False, True, True, 4.7, ["gpt-5", "claude-opus-4", "deepseek-v4"]),
    ("deepseek-v4", "DeepSeek v4", "AI Chatbot", "DeepSeek's frontier model delivering near-GPT-5 performance at dramatically lower cost.", "Freemium", "Free tier, API at fraction of frontier model pricing", ["Near-frontier reasoning", "Advanced math and science", "Open-source weights", "Extremely efficient inference", "Multilingual support"], ["Exceptional price-performance ratio", "Open-source availability", "Strong reasoning"], ["Data sovereignty concerns", "Smaller support ecosystem", "Less refined safety features"], "https://chat.deepseek.com", False, True, True, 4.6, ["gpt-5", "claude-opus-4", "llama-4"]),
    ("you-com", "You.com", "AI Search", "AI-powered search platform offering multiple AI modes and tools beyond traditional search.", "Freemium", "Free tier, You Pro at $15/mo", ["AI-powered search with citations", "Multiple AI chat modes", "Image generation built-in", "Code generation mode", "Research mode for deep dives"], ["Versatile AI tool suite", "Good citation system", "Affordable Pro tier"], ["Smaller user base than competitors", "Less refined than Perplexity", "Limited integrations"], "https://you.com", True, True, True, 4.2, ["perplexity", "chatgpt", "gemini"]),

    # AI Coding Tools
    ("cursor", "Cursor", "AI Coding", "AI-first code editor built on VS Code with deep AI integration for code generation and editing.", "Freemium", "Free tier with limits, Pro at $20/mo, Business at $40/user/mo", ["AI-powered code completion", "Multi-file editing with AI", "Codebase-aware chat", "Tab completion and suggestions", "Custom AI rules configuration"], ["Best-in-class AI coding experience", "Familiar VS Code interface", "Excellent multi-file editing", "Active development and updates"], ["Subscription required for full features", "Can be resource-intensive", "Occasional AI hallucinations"], "https://cursor.com", True, True, True, 4.8, ["github-copilot", "windsurf", "claude-code"]),
    ("github-copilot", "GitHub Copilot", "AI Coding", "GitHub's AI pair programmer providing code suggestions directly in your IDE.", "Paid", "Individual at $10/mo, Business at $19/user/mo, Enterprise at $39/user/mo", ["Inline code suggestions", "Chat interface in IDE", "Pull request summaries", "CLI assistance", "Multi-model support"], ["Seamless GitHub integration", "Wide IDE support", "Large training dataset", "Enterprise compliance features"], ["Monthly subscription required", "Suggestions can be generic", "Privacy concerns with code"], "https://github.com/features/copilot", True, True, True, 4.6, ["cursor", "windsurf", "tabnine"]),
    ("windsurf", "Windsurf", "AI Coding", "AI-powered IDE offering agentic coding with flow-based workflows for software development.", "Freemium", "Free tier, Pro at $15/mo, Enterprise custom", ["Agentic coding capabilities", "Flow-based AI workflows", "Multi-file context awareness", "Terminal integration", "Cascade AI assistant"], ["Competitive pricing", "Strong agentic features", "Good multi-file editing"], ["Newer with smaller community", "Fewer extensions than VS Code", "Occasional stability issues"], "https://windsurf.com", True, True, True, 4.5, ["cursor", "github-copilot", "claude-code"]),
    ("devin", "Devin", "AI Coding", "Cognition's autonomous AI software engineer capable of planning and executing complex engineering tasks.", "Paid", "Team plans starting at $500/mo", ["Autonomous task completion", "Full development environment", "Planning and execution pipeline", "Browser and terminal access", "Git integration"], ["Fully autonomous coding agent", "Handles complex multi-step tasks", "Integrates with existing workflows"], ["Expensive for individuals", "Not always reliable for complex tasks", "Less developer control"], "https://devin.ai", True, True, True, 4.3, ["claude-code", "cursor", "replit-agent"]),
    ("tabnine", "Tabnine", "AI Coding", "Privacy-first AI code assistant that can run locally for secure enterprise code completion.", "Freemium", "Free tier, Pro at $12/mo, Enterprise custom", ["Local model execution", "Privacy-first architecture", "Whole-line completions", "Custom model training", "Wide IDE support"], ["Enterprise-grade privacy", "Runs locally on device", "No code sent to cloud"], ["Less capable than cloud-based alternatives", "Local models need resources", "Smaller feature set"], "https://tabnine.com", True, True, True, 4.2, ["github-copilot", "cursor", "cody"]),
    ("cody", "Sourcegraph Cody", "AI Coding", "Sourcegraph's AI coding assistant with superior codebase understanding through code intelligence.", "Freemium", "Free tier, Pro at $9/mo, Enterprise custom", ["Codebase-wide context", "Code search integration", "Explain code functionality", "Unit test generation", "Multiple LLM support"], ["Deep codebase understanding", "Excellent code search", "Affordable pricing"], ["Requires Sourcegraph for full power", "Smaller community", "Less polished than Cursor"], "https://sourcegraph.com/cody", True, True, True, 4.3, ["cursor", "github-copilot", "tabnine"]),
    ("claude-code", "Claude Code", "AI Coding", "Anthropic's terminal-based agentic coding tool with deep reasoning for autonomous development.", "Paid", "Included with Claude Pro, usage-based API pricing", ["Terminal-native interface", "Deep code reasoning", "Autonomous multi-file editing", "Git-aware operations", "Extended thinking for complex tasks"], ["Superior code reasoning", "Autonomous task completion", "Terminal-native workflow"], ["Terminal-only interface", "Requires Claude subscription", "Can be slow for simple tasks"], "https://claude.ai/code", True, True, True, 4.7, ["cursor", "devin", "aider"]),
    ("aider", "Aider", "AI Coding", "Open-source terminal-based AI pair programming tool supporting multiple LLM providers.", "Open Source", "Free, bring your own API keys", ["Terminal-based pair programming", "Multi-LLM provider support", "Git-aware editing", "Voice coding support", "Automatic commit messages"], ["Free and open-source", "Works with any LLM provider", "Excellent git integration"], ["Terminal-only interface", "Requires own API keys", "Steep learning curve"], "https://aider.chat", True, True, True, 4.5, ["claude-code", "cursor", "cody"]),
    ("amazon-codewhisperer", "Amazon CodeWhisperer", "AI Coding", "AWS's AI code assistant with deep integration into Amazon Web Services and security scanning.", "Freemium", "Free Individual tier, Professional at $19/user/mo", ["AWS service integration", "Security vulnerability scanning", "Code reference tracking", "Multiple language support", "IDE plugins"], ["Generous free tier", "Strong AWS integration", "Built-in security scanning"], ["Best mainly for AWS development", "Less capable for general coding", "Fewer features than Cursor"], "https://aws.amazon.com/codewhisperer", True, True, True, 4.1, ["github-copilot", "cursor", "tabnine"]),
    ("replit-agent", "Replit Agent", "AI Coding", "Replit's AI agent that builds full applications from natural language descriptions in the browser.", "Freemium", "Free tier, Replit Core at $20/mo, Teams custom pricing", ["Natural language app building", "Built-in hosting and deployment", "Database integration", "Real-time collaboration", "Mobile app support"], ["No setup required", "Instant deployment", "Great for beginners"], ["Limited for complex applications", "Vendor lock-in", "Performance limitations"], "https://replit.com", True, True, True, 4.3, ["bolt", "lovable", "v0"]),
    ("copilot-workspace", "Copilot Workspace", "AI Coding", "GitHub's AI-powered development environment for planning and implementing code changes from issues.", "Paid", "Included with GitHub Copilot Enterprise", ["Issue-to-code workflow", "AI-generated implementation plans", "Multi-file code generation", "GitHub-native experience", "Pull request creation"], ["Deep GitHub integration", "Structured planning approach", "Enterprise-grade"], ["Enterprise-only pricing", "Limited to GitHub ecosystem", "Still evolving features"], "https://github.com/features/copilot", False, True, True, 4.2, ["devin", "cursor", "claude-code"]),

    # AI App Builders
    ("bolt", "Bolt", "AI App Builder", "AI-powered app builder that generates full-stack applications from natural language prompts.", "Freemium", "Free tier, Pro at $20/mo, Team at $40/user/mo", ["Full-stack app generation", "Multiple framework support", "Real-time preview", "One-click deployment", "Code export"], ["Fast prototyping", "No coding required", "Good framework support"], ["Limited customization", "Generated code quality varies", "Not for complex apps"], "https://bolt.new", True, True, True, 4.4, ["lovable", "v0", "gptengineer"]),
    ("lovable", "Lovable", "AI App Builder", "AI app builder focused on generating beautiful, polished UI applications from text descriptions.", "Freemium", "Free tier, Pro at $20/mo, Team custom pricing", ["Beautiful UI generation", "React and Tailwind output", "Supabase integration", "GitHub sync", "Real-time collaboration"], ["High-quality UI output", "Good design defaults", "Easy to iterate"], ["Limited backend capabilities", "Supabase dependency for backend", "Can be slow for large apps"], "https://lovable.dev", True, True, True, 4.5, ["bolt", "v0", "gptengineer"]),
    ("v0", "v0", "AI App Builder", "Vercel's AI tool for generating production-ready React UI components and pages with shadcn/ui.", "Freemium", "Free tier, Premium at $20/mo", ["React component generation", "shadcn/ui integration", "Vercel deployment", "Code export and editing", "Multiple framework support"], ["Production-quality components", "Vercel ecosystem integration", "Clean code output"], ["Focused on UI components only", "Limited backend generation", "Vercel-centric"], "https://v0.dev", True, True, True, 4.6, ["bolt", "lovable", "gptengineer"]),
    ("gptengineer", "GPT Engineer", "AI App Builder", "AI tool that generates complete application codebases from natural language project descriptions.", "Freemium", "Free tier, Pro at $20/mo", ["Full codebase generation", "Project scaffolding", "Multiple language support", "Interactive refinement", "GitHub integration"], ["Good project structure", "Interactive development flow", "Multiple frameworks"], ["Generated code needs review", "Less polished UI than Lovable", "Limited deployment options"], "https://gptengineer.app", True, True, True, 4.2, ["bolt", "lovable", "v0"]),
    ("create-xyz", "Create.xyz", "AI App Builder", "Visual AI app builder enabling non-technical users to create web applications without code.", "Freemium", "Free tier, Pro at $19/mo", ["Visual app building", "No-code interface", "Template library", "Database built-in", "Custom domain support"], ["Very beginner-friendly", "No coding knowledge needed", "Quick to deploy"], ["Limited customization", "Not suitable for complex apps", "Vendor lock-in"], "https://create.xyz", True, True, True, 4.1, ["bolt", "lovable", "bubble"]),
    ("bubble", "Bubble", "AI App Builder", "Visual programming platform for building web applications without code with AI-assisted features.", "Freemium", "Free tier, Starter at $29/mo, Growth at $119/mo", ["Visual programming interface", "Database and workflow builder", "Plugin marketplace", "API connector", "Responsive design tools"], ["Powerful no-code platform", "Large plugin ecosystem", "Scalable applications"], ["Steep learning curve", "Can get expensive at scale", "Performance limitations"], "https://bubble.io", True, True, True, 4.3, ["create-xyz", "retool-ai", "bolt"]),

    # AI Writing Tools
    ("jasper", "Jasper", "AI Writing", "Enterprise AI content platform for marketing teams with brand voice control and templates.", "Paid", "Creator at $49/mo, Pro at $69/mo, Business custom", ["Brand voice customization", "Marketing templates library", "Team collaboration", "SEO optimization mode", "Campaign workflows"], ["Purpose-built for marketing", "Strong brand voice control", "Great template library"], ["Expensive compared to alternatives", "Can produce generic content", "Overkill for individuals"], "https://jasper.ai", True, True, True, 4.4, ["copy-ai", "writer", "writesonic"]),
    ("copy-ai", "Copy.ai", "AI Writing", "AI-powered copywriting tool focused on sales and marketing content with workflow automation.", "Freemium", "Free tier, Pro at $49/mo, Enterprise custom", ["Sales copy generation", "Workflow automation", "Multiple content types", "Brand voice settings", "Team collaboration"], ["Good for sales content", "Workflow automation features", "Reasonable pricing"], ["Quality inconsistent", "Free tier very limited", "Less enterprise features"], "https://copy.ai", True, True, True, 4.2, ["jasper", "writesonic", "rytr"]),
    ("writer", "Writer", "AI Writing", "Enterprise AI writing platform with governance, compliance, and brand consistency tools.", "Paid", "Team at $18/user/mo, Enterprise custom pricing", ["Enterprise governance", "Brand style guide enforcement", "Compliance checking", "API access", "Team management"], ["Best enterprise governance", "Strong compliance features", "Custom AI models"], ["Expensive for small teams", "Complex setup", "Overkill for individuals"], "https://writer.com", True, True, True, 4.3, ["jasper", "copy-ai", "grammarly"]),
    ("writesonic", "Writesonic", "AI Writing", "AI content creation suite with SEO tools, image generation, and chatbot builder included.", "Freemium", "Free tier, Individual at $16/mo, Team at $13/user/mo", ["SEO content optimization", "AI image generation", "Chatbot builder", "Multiple content types", "Brand voice settings"], ["Affordable pricing", "Comprehensive feature set", "Good SEO integration"], ["Quality varies by content type", "Interface can be cluttered", "Limited free tier"], "https://writesonic.com", True, True, True, 4.1, ["jasper", "copy-ai", "rytr"]),
    ("rytr", "Rytr", "AI Writing", "Budget-friendly AI writing assistant for generating various content types quickly.", "Freemium", "Free tier with 10K chars/mo, Unlimited at $9/mo, Premium at $29/mo", ["40+ content templates", "Multiple tone options", "Built-in plagiarism checker", "Browser extension", "Multi-language support"], ["Most affordable option", "Simple interface", "Good for basic content"], ["Lower quality than premium tools", "Limited customization", "Basic features compared to Jasper"], "https://rytr.me", True, True, True, 3.9, ["copy-ai", "writesonic", "jasper"]),
    ("grammarly", "Grammarly", "AI Writing", "AI writing assistant for grammar checking, style improvement, and content generation.", "Freemium", "Free tier, Premium at $12/mo, Business at $15/user/mo", ["Grammar and spell checking", "Tone detection", "AI text generation", "Plagiarism detection", "Browser and app integration"], ["Industry-standard writing tool", "Excellent grammar checking", "Works everywhere via plugins"], ["AI generation is basic", "Premium required for full features", "Can be overly prescriptive"], "https://grammarly.com", True, True, True, 4.5, ["writer", "hemingway", "notion-ai"]),
    ("hemingway", "Hemingway Editor", "AI Writing", "Writing tool focused on improving readability by highlighting complex sentences and passive voice.", "Freemium", "Free web version, Desktop app at $19.99 one-time", ["Readability scoring", "Complex sentence highlighting", "Passive voice detection", "Word count and read time", "Formatting tools"], ["Simple and focused tool", "Great for improving clarity", "One-time purchase option"], ["Limited to readability editing", "No AI content generation", "Basic feature set"], "https://hemingwayapp.com", True, False, True, 4.2, ["grammarly", "writer", "notion-ai"]),
    ("notion-ai", "Notion AI", "AI Writing", "AI assistant integrated into Notion for writing, summarizing, and organizing workspace content.", "Paid", "Included with Notion plans, AI add-on at $8/member/mo", ["In-workspace AI assistant", "Content summarization", "Writing assistance", "Translation features", "Database autofill"], ["Seamless Notion integration", "Great for documentation", "Useful for teams"], ["Requires Notion subscription", "AI add-on costs extra", "Limited outside Notion"], "https://notion.so/product/ai", True, True, True, 4.4, ["clickup-ai", "coda-ai", "jasper"]),

    # AI Image Generation
    ("midjourney", "Midjourney", "AI Image Generation", "Leading AI image generator known for stunning artistic quality through Discord-based interface.", "Paid", "Basic at $10/mo, Standard at $30/mo, Pro at $60/mo", ["Artistic image generation", "Style consistency controls", "Upscaling and variations", "Pan and zoom features", "Describe image tool"], ["Best artistic quality", "Consistent style output", "Active community"], ["Discord-only interface", "No API access", "Monthly subscription required"], "https://midjourney.com", True, True, True, 4.8, ["dall-e", "stable-diffusion", "leonardo-ai"]),
    ("dall-e", "DALL-E", "AI Image Generation", "OpenAI's image generation model integrated into ChatGPT for easy text-to-image creation.", "Paid", "Included with ChatGPT Plus, API usage-based pricing", ["Text-to-image generation", "Image editing and inpainting", "ChatGPT integration", "API access", "Style and quality controls"], ["Easy ChatGPT integration", "Good prompt adherence", "Simple to use"], ["Less artistic than Midjourney", "Limited free generation", "API can be expensive"], "https://openai.com/dall-e-3", True, True, True, 4.5, ["midjourney", "stable-diffusion", "adobe-firefly"]),
    ("stable-diffusion", "Stable Diffusion", "AI Image Generation", "Open-source AI image generation model offering unlimited free local generation with full customization.", "Open Source", "Free for local use, cloud services vary", ["Open-source model weights", "Local generation support", "ControlNet and LoRA support", "Extensive community models", "ComfyUI workflow builder"], ["Completely free and open-source", "Unlimited local generation", "Massive customization options"], ["Requires technical setup", "Needs powerful GPU", "Steeper learning curve"], "https://stability.ai", True, True, True, 4.6, ["midjourney", "dall-e", "flux"]),
    ("adobe-firefly", "Adobe Firefly", "AI Image Generation", "Adobe's commercially safe AI image generator integrated across Creative Cloud applications.", "Freemium", "Free tier with limits, included in Creative Cloud at $54.99/mo", ["Commercially safe generation", "Creative Cloud integration", "Generative fill in Photoshop", "Text effects generation", "Structure reference"], ["Commercially safe to use", "Seamless Adobe integration", "Professional quality output"], ["Creative Cloud subscription for full use", "Less artistic than Midjourney", "Limited free credits"], "https://firefly.adobe.com", True, True, True, 4.4, ["midjourney", "dall-e", "canva-ai"]),
    ("leonardo-ai", "Leonardo AI", "AI Image Generation", "AI image platform offering fine-tuning, real-time generation, and extensive creative controls.", "Freemium", "Free tier with 150 tokens/day, Artisan at $12/mo, Unlimited at $30/mo", ["Real-time generation canvas", "Model fine-tuning", "AI canvas editing", "Motion generation", "Style reference"], ["Great creative controls", "Fine-tuning capability", "Real-time generation"], ["Credit system can be limiting", "Quality varies by model", "Complex interface"], "https://leonardo.ai", True, True, True, 4.4, ["midjourney", "stable-diffusion", "ideogram"]),
    ("ideogram", "Ideogram", "AI Image Generation", "AI image generator specializing in accurate text rendering within generated images.", "Freemium", "Free tier with 10 images/day, Plus at $8/mo, Pro at $20/mo", ["Accurate text in images", "Multiple style presets", "High-resolution output", "Batch generation", "Image editing tools"], ["Best text-in-image accuracy", "Affordable pricing", "Good image quality"], ["Less artistic than Midjourney", "Smaller community", "Limited advanced features"], "https://ideogram.ai", True, True, True, 4.3, ["midjourney", "dall-e", "flux"]),
    ("flux", "Flux", "AI Image Generation", "Open-source image generation model known for impressive photorealism and local deployment options.", "Open Source", "Free for local use, API pricing varies by provider", ["Photorealistic generation", "Open-source architecture", "Local deployment support", "Multiple model variants", "Fast inference"], ["Excellent photorealism", "Free and open-source", "Active development"], ["Requires technical setup", "GPU-intensive", "Smaller ecosystem than SD"], "https://blackforestlabs.ai", True, True, True, 4.5, ["stable-diffusion", "midjourney", "dall-e"]),

    # AI Video
    ("runway", "Runway", "AI Video", "Professional AI video generation and editing platform for creative video production.", "Freemium", "Free tier, Standard at $12/user/mo, Pro at $28/user/mo", ["Text-to-video generation", "Video-to-video transformation", "AI video editing tools", "Motion brush", "Green screen removal"], ["Professional-grade tools", "Multiple AI video features", "Good for creative work"], ["Credits consumed quickly", "Generation can be slow", "Expensive for heavy use"], "https://runwayml.com", True, True, True, 4.5, ["pika", "sora", "kling"]),
    ("pika", "Pika", "AI Video", "Accessible AI video generation platform for creating and editing short video content.", "Freemium", "Free tier with 250 credits, Standard at $8/mo, Pro at $28/mo", ["Text-to-video generation", "Image-to-video animation", "Video editing and extension", "Lip sync feature", "Multiple aspect ratios"], ["Easy to use interface", "Affordable pricing", "Good for short content"], ["Lower quality than Runway", "Limited video length", "Credits run out fast"], "https://pika.art", True, True, True, 4.2, ["runway", "sora", "kling"]),
    ("synthesia", "Synthesia", "AI Video", "Enterprise AI video platform for creating professional avatar-based training and corporate videos.", "Paid", "Starter at $22/mo, Creator at $67/mo, Enterprise custom", ["160+ AI avatars", "140+ languages", "Custom avatar creation", "Script-to-video workflow", "Brand kit integration"], ["Professional corporate videos", "Multilingual support", "No filming required"], ["Avatars can look artificial", "Limited creative flexibility", "Expensive for small teams"], "https://synthesia.io", True, True, True, 4.4, ["heygen", "descript", "runway"]),
    ("heygen", "HeyGen", "AI Video", "AI avatar video platform with real-time translation and personalized video creation at scale.", "Freemium", "Free tier, Creator at $24/mo, Business at $72/mo", ["AI avatar creation", "Real-time video translation", "Personalized videos at scale", "Voice cloning", "Interactive avatar"], ["Strong avatar customization", "Excellent translation feature", "Good for outreach"], ["Can look robotic", "Higher price point", "Learning curve for features"], "https://heygen.com", True, True, True, 4.3, ["synthesia", "descript", "runway"]),
    ("sora", "Sora", "AI Video", "OpenAI's cinematic AI video generator creating high-quality videos from text prompts.", "Paid", "Included with ChatGPT Plus and Pro plans", ["Cinema-quality generation", "Text-to-video creation", "Long-form video support", "Style and camera controls", "Storyboard mode"], ["Stunning video quality", "OpenAI ecosystem integration", "Strong prompt understanding"], ["Limited availability", "Slow generation times", "High compute requirements"], "https://openai.com/sora", True, True, True, 4.6, ["runway", "pika", "kling"]),
    ("kling", "Kling AI", "AI Video", "AI video generation platform offering high-fidelity video creation with competitive pricing.", "Freemium", "Free tier, Standard at $8/mo, Pro at $28/mo", ["High-fidelity video generation", "Image-to-video conversion", "Long clip generation", "Motion control", "Face animation"], ["Impressive generation quality", "Competitive pricing", "Longer video clips"], ["Newer platform with less polish", "Limited editing tools", "Account setup complexity"], "https://klingai.com", True, True, True, 4.3, ["runway", "sora", "pika"]),
    ("descript", "Descript", "AI Video", "AI-powered video and podcast editing platform using text-based editing workflows.", "Freemium", "Free tier, Hobbyist at $24/mo, Business at $33/mo", ["Text-based video editing", "AI filler word removal", "Studio sound enhancement", "Screen recording", "Transcription and captions"], ["Revolutionary text-based editing", "Great for podcasts", "Easy screen recording"], ["Limited creative video effects", "Can be slow with large files", "Learning curve"], "https://descript.com", True, True, True, 4.5, ["runway", "synthesia", "otter-ai"]),

    # AI Audio
    ("eleven-labs", "ElevenLabs", "AI Audio", "Leading AI voice technology platform offering realistic text-to-speech and voice cloning.", "Freemium", "Free tier, Starter at $5/mo, Creator at $22/mo, Pro at $99/mo", ["Ultra-realistic voice synthesis", "Voice cloning technology", "29+ languages", "Voice library marketplace", "API access"], ["Most realistic AI voices", "Excellent voice cloning", "Wide language support"], ["Premium voices require paid tier", "Ethical voice cloning concerns", "Usage limits on lower tiers"], "https://elevenlabs.io", True, True, True, 4.7, ["play-ht", "murf-ai", "suno"]),
    ("play-ht", "Play.ht", "AI Audio", "AI voice generator with natural-sounding text-to-speech and podcast hosting capabilities.", "Freemium", "Free tier, Creator at $31/mo, Unlimited at $99/mo", ["Natural text-to-speech", "Voice cloning", "Podcast hosting", "API access", "Multiple voice models"], ["Wide voice selection", "Good podcast integration", "Reasonable pricing"], ["Less natural than ElevenLabs", "Interface can be cluttered", "Credit system on lower tiers"], "https://play.ht", True, True, True, 4.2, ["eleven-labs", "murf-ai", "descript"]),
    ("murf-ai", "Murf AI", "AI Audio", "Enterprise AI voiceover platform designed for professional presentations and corporate content.", "Freemium", "Free tier, Creator at $26/mo, Business at $59/mo", ["Professional voiceover generation", "Video sync capability", "Multi-accent support", "Team collaboration", "Pronunciation editing"], ["Clean professional output", "Good for corporate use", "Easy to use interface"], ["Less natural than ElevenLabs", "Limited voice customization", "Accent options could be broader"], "https://murf.ai", True, True, True, 4.1, ["eleven-labs", "play-ht", "descript"]),
    ("suno", "Suno", "AI Music", "AI music generator that creates complete songs with vocals, instruments, and lyrics from prompts.", "Freemium", "Free tier with 5 songs/day, Pro at $10/mo, Premier at $30/mo", ["Full song generation", "Custom lyrics support", "Multiple genres and styles", "Vocal synthesis", "Remix capabilities"], ["Creates complete songs", "Easy to use", "Surprisingly good quality"], ["Songs can sound formulaic", "Limited editing control", "Copyright concerns"], "https://suno.com", True, True, True, 4.4, ["udio", "eleven-labs", "descript"]),
    ("udio", "Udio", "AI Music", "AI music creation platform offering detailed control over musical style and composition.", "Freemium", "Free tier with 10 songs/mo, Standard at $10/mo, Pro at $30/mo", ["Detailed style control", "High-quality audio output", "Lyrics generation", "Multiple genre support", "Extend and remix tools"], ["More musical control than Suno", "High audio quality", "Good genre variety"], ["Smaller community", "Slower generation", "Limited free tier"], "https://udio.com", True, True, True, 4.3, ["suno", "eleven-labs", "play-ht"]),

    # AI Automation
    ("zapier", "Zapier", "AI Automation", "Leading workflow automation platform connecting 7000+ apps with AI-powered features.", "Freemium", "Free tier with 100 tasks/mo, Starter at $19.99/mo, Professional at $49/mo", ["7000+ app integrations", "AI-powered workflow builder", "Multi-step automations", "Conditional logic", "Scheduled triggers"], ["Largest integration library", "Easy to set up", "Reliable execution"], ["Gets expensive at scale", "Complex workflows need higher tiers", "Per-task pricing adds up"], "https://zapier.com", True, True, True, 4.6, ["make", "n8n", "activepieces"]),
    ("make", "Make", "AI Automation", "Visual workflow automation platform with powerful scenario building and AI integration.", "Freemium", "Free tier with 1000 ops/mo, Core at $9/mo, Pro at $16/mo", ["Visual scenario builder", "HTTP/Webhook modules", "Error handling", "Data transformation", "Scheduled execution"], ["More powerful visual builder", "Better pricing for complex workflows", "Flexible data manipulation"], ["Steeper learning curve", "Fewer integrations than Zapier", "Can be complex to debug"], "https://make.com", True, True, True, 4.5, ["zapier", "n8n", "activepieces"]),
    ("n8n", "n8n", "AI Automation", "Open-source workflow automation platform with self-hosting and unlimited workflows.", "Open Source", "Free self-hosted, Cloud Starter at $20/mo, Pro at $50/mo", ["Open-source and self-hostable", "Unlimited workflows on self-hosted", "Code nodes for custom logic", "AI agent capabilities", "220+ integrations"], ["Free self-hosted option", "Unlimited workflows", "Maximum flexibility with code"], ["Requires technical setup for self-hosting", "Fewer integrations than Zapier", "Community support only on free tier"], "https://n8n.io", True, True, True, 4.5, ["zapier", "make", "activepieces"]),
    ("activepieces", "Activepieces", "AI Automation", "Open-source automation platform with no per-task limits and self-hosting support.", "Open Source", "Free self-hosted, Cloud Pro at $10/mo", ["Open-source platform", "No per-task pricing", "Visual flow builder", "Self-hosting option", "Growing integration library"], ["No per-task costs", "Open-source flexibility", "Simple interface"], ["Smaller integration library", "Newer and less mature", "Community still growing"], "https://activepieces.com", True, True, True, 4.2, ["n8n", "zapier", "make"]),
    ("power-automate", "Power Automate", "AI Automation", "Microsoft's automation platform deeply integrated with Microsoft 365 and enterprise systems.", "Paid", "Per user at $15/user/mo, Per flow at $100/flow/mo", ["Microsoft 365 deep integration", "Desktop and cloud flows", "AI Builder integration", "RPA capabilities", "Dataverse connection"], ["Best for Microsoft shops", "Desktop automation support", "Enterprise compliance"], ["Complex pricing model", "Steep learning curve", "Best only within Microsoft ecosystem"], "https://powerautomate.microsoft.com", True, True, True, 4.2, ["zapier", "make", "n8n"]),
    ("ifttt", "IFTTT", "AI Automation", "Simple automation platform for connecting apps and devices with easy if-then rules.", "Freemium", "Free tier with 2 applets, Pro at $3.49/mo, Pro+ at $14.99/mo", ["Simple if-then automations", "Smart home integration", "700+ app connections", "Location triggers", "Widget support"], ["Very easy to use", "Great for smart home", "Affordable Pro tier"], ["Limited to simple automations", "Fewer business integrations", "No complex workflows"], "https://ifttt.com", True, True, True, 4.0, ["zapier", "make", "n8n"]),

    # AI Agent Frameworks
    ("langchain", "LangChain", "AI Agent Framework", "The most popular framework for building LLM-powered applications with chains and agents.", "Open Source", "Free, LangSmith platform has paid tiers starting at $39/mo", ["Chain and agent composition", "Tool and retriever integrations", "Memory management", "LangSmith observability", "LangGraph for complex agents"], ["Largest LLM framework ecosystem", "Comprehensive documentation", "Active community"], ["Steep learning curve", "Frequent breaking changes", "Can be over-engineered"], "https://langchain.com", True, True, True, 4.4, ["llamaindex", "crewai", "langgraph"]),
    ("langgraph", "LangGraph", "AI Agent Framework", "LangChain's framework for building stateful, multi-step AI agent workflows with graph architecture.", "Open Source", "Free, LangSmith platform has paid tiers", ["Graph-based agent workflows", "Stateful execution", "Human-in-the-loop support", "Streaming support", "LangSmith integration"], ["Production-grade orchestration", "Excellent state management", "Good debugging tools"], ["Complex learning curve", "Tightly coupled with LangChain", "Documentation still evolving"], "https://langchain.com/langgraph", True, True, True, 4.3, ["langchain", "crewai", "autogen"]),
    ("crewai", "CrewAI", "AI Agent Framework", "Framework for orchestrating multi-agent AI teams with role-based agent collaboration.", "Open Source", "Free open-source, Enterprise platform pricing available", ["Role-based agent teams", "Task delegation system", "Tool integration", "Memory and context sharing", "Process orchestration"], ["Intuitive agent team concept", "Easy to get started", "Good documentation"], ["Less granular control than LangGraph", "Newer framework", "Limited enterprise features"], "https://crewai.com", True, True, True, 4.3, ["langgraph", "autogen", "langchain"]),
    ("autogen", "AutoGen", "AI Agent Framework", "Microsoft's framework for building multi-agent conversational AI systems.", "Open Source", "Free, Microsoft-backed", ["Conversational agent patterns", "Group chat orchestration", "Code execution support", "Human-in-the-loop", "Flexible agent configuration"], ["Microsoft backing and support", "Good for conversational patterns", "Active development"], ["Can be complex to configure", "Documentation gaps", "Less production-focused"], "https://microsoft.github.io/autogen", True, True, True, 4.2, ["crewai", "langgraph", "openai-swarm"]),
    ("openai-swarm", "OpenAI Swarm", "AI Agent Framework", "Lightweight experimental framework from OpenAI for agent handoff patterns.", "Open Source", "Free, educational/experimental", ["Lightweight agent handoffs", "Simple agent definitions", "Function calling integration", "Minimal boilerplate", "OpenAI model integration"], ["Very simple to understand", "Clean API design", "Good for learning"], ["Experimental and not production-ready", "Limited features", "Minimal error handling"], "https://github.com/openai/swarm", False, False, True, 3.8, ["crewai", "autogen", "langgraph"]),
    ("llamaindex", "LlamaIndex", "AI Agent Framework", "Framework specializing in connecting LLMs with data through advanced retrieval-augmented generation.", "Open Source", "Free, LlamaCloud has paid tiers", ["Advanced RAG pipelines", "Data connector library", "Index management", "Query engines", "Agent framework"], ["Best-in-class RAG", "Excellent data connectors", "Good documentation"], ["Less general than LangChain", "Agent framework still maturing", "Can be complex for simple use cases"], "https://llamaindex.ai", True, True, True, 4.4, ["langchain", "crewai", "dify"]),
    ("dify", "Dify", "AI Agent Framework", "Visual LLM application builder enabling no-code creation of AI agents and workflows.", "Open Source", "Free self-hosted, Cloud Sandbox free, Pro at $59/mo", ["Visual workflow builder", "RAG pipeline builder", "Agent creation tools", "Model management", "API deployment"], ["No-code AI app building", "Self-hosting option", "Visual development"], ["Less flexible than code frameworks", "Complex apps need custom code", "Newer platform"], "https://dify.ai", True, True, True, 4.3, ["langchain", "crewai", "llamaindex"]),

    # AI Design
    ("figma-ai", "Figma AI", "AI Design", "AI features integrated into Figma for enhanced design workflows and component generation.", "Paid", "Included with Figma plans, Professional at $12/editor/mo", ["AI-powered design suggestions", "Auto layout improvements", "Component generation", "Design system AI", "Prototype AI features"], ["Seamless Figma integration", "Professional design tool", "Great for teams"], ["Requires Figma subscription", "AI features still evolving", "Limited generation capabilities"], "https://figma.com", True, True, True, 4.5, ["canva-ai", "framer", "adobe-firefly"]),
    ("framer", "Framer", "AI Design", "AI-powered website builder that turns designs into live, published responsive websites.", "Freemium", "Free tier, Mini at $5/mo, Basic at $15/mo, Pro at $25/mo", ["AI website generation", "Responsive design", "CMS built-in", "Animation tools", "Custom code support"], ["Beautiful output quality", "Fast design-to-site workflow", "Good animation support"], ["CMS limitations", "Complex sites need workarounds", "Learning curve for advanced features"], "https://framer.com", True, True, True, 4.5, ["webflow", "figma-ai", "wix-ai"]),
    ("canva-ai", "Canva AI", "AI Design", "AI-powered design platform for creating marketing materials, presentations, and social content.", "Freemium", "Free tier, Pro at $12.99/mo, Teams at $14.99/user/mo", ["AI image generation", "Magic Design templates", "Brand kit management", "Social media sizing", "Video editing"], ["Very easy to use", "Great template library", "Affordable pricing"], ["Limited for professional design", "AI generation is basic", "Export quality limitations"], "https://canva.com", True, True, True, 4.6, ["figma-ai", "adobe-firefly", "beautiful-ai"]),
    ("beautiful-ai", "Beautiful.ai", "AI Design", "AI presentation tool that automatically formats and designs professional slides.", "Paid", "Pro at $12/mo, Team at $40/user/mo, Enterprise custom", ["Auto-formatting slides", "Smart templates", "Design AI suggestions", "Team collaboration", "Brand controls"], ["Consistently beautiful slides", "Saves design time", "Easy to use"], ["Limited template customization", "Less flexible than PowerPoint", "Fewer animation options"], "https://beautiful.ai", True, True, True, 4.2, ["gamma", "tome", "canva-ai"]),
    ("tome", "Tome", "AI Design", "AI-powered presentation platform for creating narrative-driven presentations and documents.", "Freemium", "Free tier, Professional at $16/mo, Enterprise custom", ["AI presentation generation", "Narrative flow design", "Embedded content support", "Collaboration features", "Analytics tracking"], ["Great narrative presentations", "Modern aesthetic", "Easy AI generation"], ["Limited export options", "Less formal than PowerPoint", "Smaller template library"], "https://tome.app", True, True, True, 4.1, ["gamma", "beautiful-ai", "canva-ai"]),
    ("gamma", "Gamma", "AI Design", "AI tool for creating presentations, documents, and websites from prompts with smart formatting.", "Freemium", "Free tier with AI credits, Plus at $8/user/mo, Pro at $15/user/mo", ["AI presentation generation", "Document and webpage modes", "Smart formatting", "Nested cards layout", "Theme customization"], ["Versatile output formats", "Good AI generation", "Affordable pricing"], ["Less polished than traditional tools", "Limited offline access", "Export limitations"], "https://gamma.app", True, True, True, 4.3, ["beautiful-ai", "tome", "canva-ai"]),
    ("webflow", "Webflow", "AI Design", "Professional website builder with AI features, CMS, and hosting for complex web projects.", "Freemium", "Free tier, Basic at $14/mo, CMS at $23/mo, Business at $39/mo", ["Visual web development", "CMS capabilities", "E-commerce support", "Custom interactions", "Hosting included"], ["Professional web building", "No-code complexity", "Great for agencies"], ["Steep learning curve", "Can get expensive", "E-commerce fees on top"], "https://webflow.com", True, True, True, 4.5, ["framer", "wix-ai", "squarespace-ai"]),
    ("wix-ai", "Wix AI", "AI Design", "AI-powered website builder with automated design and content generation for quick site creation.", "Freemium", "Free tier, Light at $17/mo, Core at $29/mo, Business at $36/mo", ["AI site generation", "Drag-and-drop builder", "App marketplace", "SEO tools built-in", "E-commerce support"], ["Very beginner-friendly", "AI speeds up creation", "Large app marketplace"], ["Sites can feel template-heavy", "Vendor lock-in", "Performance limitations"], "https://wix.com", True, True, True, 4.2, ["squarespace-ai", "webflow", "framer"]),
    ("squarespace-ai", "Squarespace AI", "AI Design", "Website platform with AI writing and design tools built into polished professional templates.", "Paid", "Personal at $16/mo, Business at $33/mo, Commerce at $36/mo", ["AI writing assistance", "Professional templates", "E-commerce built-in", "SEO features", "Analytics dashboard"], ["Most polished templates", "Great for small businesses", "Built-in commerce"], ["Less flexible than Webflow", "Limited AI features", "Higher starting price"], "https://squarespace.com", True, True, True, 4.3, ["wix-ai", "webflow", "framer"]),

    # AI Marketing & SEO
    ("semrush", "Semrush", "AI SEO", "Comprehensive digital marketing platform with AI-powered SEO, content, and competitive tools.", "Paid", "Pro at $139.95/mo, Guru at $249.95/mo, Business at $499.95/mo", ["Keyword research", "Site audit tools", "Competitive analysis", "Content optimization", "Rank tracking"], ["Most comprehensive SEO toolkit", "Strong competitive intelligence", "Great for agencies"], ["Expensive for individuals", "Steep learning curve", "Data can overwhelm beginners"], "https://semrush.com", True, True, True, 4.6, ["ahrefs", "surfer-seo", "clearscope"]),
    ("ahrefs", "Ahrefs", "AI SEO", "Premium SEO toolset known for the best backlink analysis and intuitive site explorer.", "Paid", "Lite at $129/mo, Standard at $249/mo, Advanced at $449/mo", ["Best backlink database", "Site explorer", "Keyword explorer", "Content explorer", "Rank tracker"], ["Superior backlink analysis", "Intuitive interface", "Accurate data"], ["Expensive starting price", "No free tier", "Content tools less developed"], "https://ahrefs.com", True, True, True, 4.7, ["semrush", "surfer-seo", "clearscope"]),
    ("surfer-seo", "Surfer SEO", "AI SEO", "AI-driven content optimization platform that analyzes top-ranking pages to improve content.", "Paid", "Essential at $89/mo, Scale at $129/mo, Enterprise custom", ["Content editor with scoring", "SERP analysis", "Keyword clustering", "Content audit", "AI writing integration"], ["Excellent content optimization", "Easy to understand scoring", "Good for content teams"], ["Focused only on content SEO", "No backlink features", "Can be prescriptive"], "https://surferseo.com", True, True, True, 4.4, ["semrush", "ahrefs", "clearscope"]),
    ("clearscope", "Clearscope", "AI SEO", "Premium content intelligence platform helping enterprises create authoritative, ranking content.", "Paid", "Essentials at $189/mo, Business at $399/mo, Enterprise custom", ["Content grading system", "Keyword discovery", "Competitor content analysis", "Google Docs integration", "Team collaboration"], ["Premium content intelligence", "Clean interface", "Strong Google Docs integration"], ["Very expensive", "No free trial", "Limited to content optimization"], "https://clearscope.io", True, True, True, 4.3, ["surfer-seo", "semrush", "ahrefs"]),
    ("hubspot-ai", "HubSpot AI", "AI Marketing", "HubSpot's AI tools for CRM, marketing automation, sales, and customer service.", "Freemium", "Free CRM, Starter at $20/mo, Professional at $890/mo", ["AI content generation", "Lead scoring", "Email personalization", "Chatbot builder", "Campaign automation"], ["All-in-one marketing platform", "Strong CRM integration", "Good for SMBs"], ["Professional tier is expensive", "Can be complex to set up", "Locked into HubSpot ecosystem"], "https://hubspot.com", True, True, True, 4.5, ["salesforce-einstein", "mailchimp-ai", "drift"]),
    ("salesforce-einstein", "Salesforce Einstein", "AI Marketing", "Salesforce's AI layer providing predictive analytics and automation across the Salesforce platform.", "Paid", "Included with Salesforce Enterprise+, add-on pricing varies", ["Predictive lead scoring", "Opportunity insights", "Email sentiment analysis", "Automated recommendations", "Custom predictions"], ["Deep Salesforce integration", "Powerful enterprise analytics", "Predictive capabilities"], ["Requires Salesforce subscription", "Complex setup", "Very expensive for small teams"], "https://salesforce.com/einstein", False, True, True, 4.4, ["hubspot-ai", "zoho-zia", "drift"]),
    ("buffer", "Buffer", "AI Social Media", "Simple social media management tool with AI-powered content suggestions and scheduling.", "Freemium", "Free for 3 channels, Essentials at $6/channel/mo, Team at $12/channel/mo", ["Social media scheduling", "AI content suggestions", "Analytics dashboard", "Link-in-bio page", "Team approval workflows"], ["Simple and intuitive", "Affordable pricing", "Good for small teams"], ["Basic analytics", "Limited integrations", "No social listening"], "https://buffer.com", True, True, True, 4.3, ["hootsuite", "sprout-social", "mailchimp-ai"]),
    ("hootsuite", "Hootsuite", "AI Social Media", "Enterprise social media management platform with AI content creation and comprehensive analytics.", "Paid", "Professional at $99/mo, Team at $249/mo, Enterprise custom", ["Multi-platform scheduling", "AI content writer", "Social listening", "Advanced analytics", "Team collaboration"], ["Comprehensive feature set", "Strong analytics", "Enterprise-ready"], ["Expensive for small teams", "Interface can be cluttered", "Free tier removed"], "https://hootsuite.com", True, True, True, 4.2, ["buffer", "sprout-social", "hubspot-ai"]),
    ("sprout-social", "Sprout Social", "AI Social Media", "Premium social media management with AI-powered analytics, listening, and engagement tools.", "Paid", "Standard at $249/mo, Professional at $399/mo, Advanced at $499/mo", ["Social listening AI", "Advanced analytics", "Smart inbox", "Campaign planning", "Employee advocacy"], ["Best-in-class analytics", "Excellent reporting", "Strong listening tools"], ["Very expensive", "Overkill for small teams", "Steep learning curve"], "https://sproutsocial.com", True, True, True, 4.4, ["hootsuite", "buffer", "hubspot-ai"]),
    ("mailchimp-ai", "Mailchimp AI", "AI Email Marketing", "Email marketing platform with AI-powered content generation, segmentation, and send optimization.", "Freemium", "Free tier up to 500 contacts, Essentials at $13/mo, Standard at $20/mo", ["AI email content generation", "Send time optimization", "Audience segmentation", "Landing page builder", "Marketing automation"], ["User-friendly interface", "Generous free tier", "Good for beginners"], ["Gets expensive with growth", "Limited automation on free tier", "Template design limitations"], "https://mailchimp.com", True, True, True, 4.3, ["klaviyo", "hubspot-ai", "buffer"]),
    ("klaviyo", "Klaviyo", "AI Email Marketing", "E-commerce-focused email and SMS marketing platform with AI-driven personalization.", "Freemium", "Free up to 250 contacts, Email starts at $20/mo, Email+SMS at $35/mo", ["E-commerce integrations", "AI product recommendations", "Predictive analytics", "Flow automation builder", "SMS marketing"], ["Best for e-commerce", "Powerful segmentation", "Great Shopify integration"], ["Expensive at scale", "Complex for beginners", "SMS adds significant cost"], "https://klaviyo.com", True, True, True, 4.5, ["mailchimp-ai", "hubspot-ai", "buffer"]),

    # AI Analytics
    ("tableau-ai", "Tableau AI", "AI Analytics", "Salesforce's business intelligence platform with AI-powered data visualization and analytics.", "Paid", "Creator at $75/user/mo, Explorer at $42/user/mo, Viewer at $15/user/mo", ["AI-powered visualization", "Natural language queries", "Data preparation", "Dashboard creation", "Embedded analytics"], ["Industry-leading visualization", "Powerful data exploration", "Large community"], ["Expensive licensing", "Steep learning curve", "Requires data preparation"], "https://tableau.com", True, True, True, 4.5, ["power-bi", "julius-ai", "datadog"]),
    ("power-bi", "Power BI", "AI Analytics", "Microsoft's business intelligence tool with AI features and deep Microsoft 365 integration.", "Freemium", "Free Desktop version, Pro at $10/user/mo, Premium at $20/user/mo", ["AI-powered insights", "Natural language Q&A", "Microsoft 365 integration", "Custom visualizations", "Dataflow preparation"], ["Affordable enterprise BI", "Strong Microsoft integration", "Good AI features"], ["Complex data modeling", "Windows-centric", "Report design limitations"], "https://powerbi.microsoft.com", True, True, True, 4.4, ["tableau-ai", "julius-ai", "datadog"]),
    ("julius-ai", "Julius AI", "AI Analytics", "AI data analysis platform that generates insights, charts, and answers from uploaded data.", "Freemium", "Free tier, Essential at $20/mo, Pro at $45/mo", ["Natural language data analysis", "Chart generation", "Data cleaning", "Multiple data sources", "Code generation for analysis"], ["Very easy to use", "No coding required", "Good chart generation"], ["Limited for complex analysis", "Data size limitations", "Less powerful than Tableau"], "https://julius.ai", True, True, True, 4.2, ["tableau-ai", "power-bi", "chatgpt"]),

    # AI Customer Support
    ("intercom-fin", "Intercom Fin", "AI Customer Support", "Intercom's AI agent that resolves support queries automatically with human-like conversation.", "Paid", "$0.99 per resolution, platform plans from $39/mo", ["AI-first support agent", "Custom answers from knowledge base", "Human handoff", "Multi-language support", "Analytics dashboard"], ["AI-first modern approach", "Pay-per-resolution model", "Great knowledge base learning"], ["Per-resolution cost adds up", "Platform fee on top", "Complex pricing"], "https://intercom.com/fin", True, True, True, 4.5, ["zendesk-ai", "drift", "freshdesk-ai"]),
    ("zendesk-ai", "Zendesk AI", "AI Customer Support", "Enterprise support platform with AI-powered ticket routing, suggestions, and automation.", "Paid", "Suite Team at $55/agent/mo, Growth at $89/agent/mo, Professional at $115/agent/mo", ["AI ticket routing", "Agent assist suggestions", "Knowledge base AI", "Omnichannel support", "Advanced reporting"], ["Enterprise-grade features", "Strong ticket management", "Comprehensive omnichannel"], ["Expensive per agent", "Complex configuration", "Slow innovation pace"], "https://zendesk.com", True, True, True, 4.3, ["intercom-fin", "freshdesk-ai", "drift"]),
    ("drift", "Drift", "AI Customer Support", "Conversational marketing and sales platform using AI chatbots for lead generation.", "Paid", "Premium starting at $2,500/mo, Enterprise custom", ["AI chatbot for leads", "Meeting scheduling", "Account-based marketing", "Revenue acceleration", "Conversational insights"], ["Great for sales teams", "Strong lead qualification", "Good meeting booking"], ["Very expensive", "Focused on sales not support", "Complex implementation"], "https://drift.com", False, True, True, 4.2, ["intercom-fin", "hubspot-ai", "zendesk-ai"]),
    ("freshdesk-ai", "Freshdesk AI", "AI Customer Support", "Affordable AI-powered help desk with ticket automation and customer self-service features.", "Freemium", "Free tier up to 10 agents, Growth at $15/agent/mo, Pro at $49/agent/mo", ["AI ticket assignment", "Canned response suggestions", "Self-service portal", "SLA management", "Freddy AI assistant"], ["Affordable pricing", "Good free tier", "Easy to set up"], ["AI features less advanced", "Limited customization", "Enterprise features lacking"], "https://freshdesk.com", True, True, True, 4.2, ["zendesk-ai", "intercom-fin", "drift"]),

    # AI Transcription
    ("otter-ai", "Otter.ai", "AI Transcription", "AI meeting assistant providing real-time transcription, summaries, and action items.", "Freemium", "Free tier with 300 min/mo, Pro at $16.99/mo, Business at $30/user/mo", ["Real-time transcription", "Meeting summaries", "Action item extraction", "Speaker identification", "Zoom/Teams/Meet integration"], ["Excellent real-time transcription", "Good meeting summaries", "Wide integration support"], ["Accuracy varies with accents", "Free tier limitations", "Audio quality dependent"], "https://otter.ai", True, True, True, 4.4, ["fireflies", "descript", "whisper"]),
    ("fireflies", "Fireflies.ai", "AI Transcription", "AI meeting assistant with transcription, search, and analytics across meeting platforms.", "Freemium", "Free tier, Pro at $18/user/mo, Business at $29/user/mo", ["Meeting transcription", "AI-powered search", "Meeting analytics", "CRM integration", "Custom topic tracking"], ["Strong analytics features", "Good CRM integration", "Searchable meeting archive"], ["Transcription less accurate than Otter", "Interface can be cluttered", "Storage limits on free tier"], "https://fireflies.ai", True, True, True, 4.2, ["otter-ai", "descript", "whisper"]),
    ("whisper", "OpenAI Whisper", "AI Transcription", "OpenAI's open-source speech recognition model for accurate multilingual transcription.", "Open Source", "Free for local use, API at $0.006/minute", ["Multi-language support", "High accuracy transcription", "Open-source model", "Local deployment", "API access via OpenAI"], ["Free and open-source", "Excellent accuracy", "99 language support"], ["Requires technical setup", "No real-time processing", "No built-in UI"], "https://github.com/openai/whisper", False, False, True, 4.6, ["otter-ai", "fireflies", "eleven-labs"]),

    # AI Development / Backend / DevOps
    ("supabase", "Supabase", "AI Development", "Open-source Firebase alternative with Postgres database, auth, storage, and AI vector features.", "Freemium", "Free tier, Pro at $25/mo, Team at $599/mo", ["Postgres database", "Authentication system", "Real-time subscriptions", "Vector embeddings support", "Edge functions"], ["Open-source and transparent", "Full SQL with Postgres", "Great developer experience"], ["Free tier resource limits", "Less mature than Firebase", "Smaller ecosystem"], "https://supabase.com", True, True, True, 4.6, ["firebase", "appwrite", "mongodb-atlas"]),
    ("firebase", "Firebase", "AI Development", "Google's app development platform with real-time database, auth, hosting, and ML capabilities.", "Freemium", "Free Spark plan, Blaze pay-as-you-go, ML features included", ["Real-time database", "Authentication", "Cloud hosting", "ML Kit", "Cloud functions"], ["Mature and reliable", "Google Cloud integration", "Great for mobile apps"], ["NoSQL only for main DB", "Vendor lock-in to Google", "Costs can spike unpredictably"], "https://firebase.google.com", True, True, True, 4.5, ["supabase", "appwrite", "mongodb-atlas"]),
    ("appwrite", "Appwrite", "AI Development", "Open-source backend-as-a-service with database, auth, storage, and cloud functions.", "Open Source", "Free self-hosted, Cloud Free tier, Pro at $15/mo", ["Self-hosted backend", "Database and auth", "Storage and functions", "Real-time updates", "Multi-runtime support"], ["Open-source and self-hostable", "Comprehensive BaaS features", "Active community"], ["Smaller ecosystem than Firebase", "Self-hosting requires maintenance", "Documentation gaps"], "https://appwrite.io", True, True, True, 4.3, ["supabase", "firebase", "mongodb-atlas"]),
    ("vercel", "Vercel", "AI Development", "Frontend cloud platform with best-in-class Next.js hosting, edge functions, and AI SDK.", "Freemium", "Free Hobby tier, Pro at $20/user/mo, Enterprise custom", ["Next.js optimized hosting", "Edge functions", "AI SDK", "Preview deployments", "Analytics built-in"], ["Best Next.js experience", "Excellent DX", "Fast global edge network"], ["Can get expensive at scale", "Bandwidth costs add up", "Vendor lock-in risk"], "https://vercel.com", True, True, True, 4.7, ["netlify", "cloudflare-pages", "firebase"]),
    ("netlify", "Netlify", "AI Development", "Web development platform with continuous deployment, serverless functions, and edge capabilities.", "Freemium", "Free tier, Pro at $19/user/mo, Enterprise custom", ["Continuous deployment", "Serverless functions", "Edge handlers", "Form handling", "Split testing"], ["Great free tier", "Easy CI/CD setup", "Framework agnostic"], ["Build minutes can run out", "Serverless function limits", "Less optimized for Next.js"], "https://netlify.com", True, True, True, 4.4, ["vercel", "cloudflare-pages", "firebase"]),
    ("cloudflare-pages", "Cloudflare Pages", "AI Development", "Cloudflare's JAMstack platform with global edge deployment and Workers integration.", "Freemium", "Free tier with unlimited sites, Pro at $20/mo, Enterprise custom", ["Global edge deployment", "Workers integration", "Unlimited bandwidth on free tier", "Git integration", "Custom domains"], ["Unlimited free bandwidth", "Fastest global network", "Great pricing"], ["Less intuitive than Vercel", "Limited build customization", "Newer with fewer features"], "https://pages.cloudflare.com", True, True, True, 4.4, ["vercel", "netlify", "firebase"]),
    ("linear", "Linear", "AI Development", "Modern project management tool designed for speed with AI-powered features for engineering teams.", "Freemium", "Free tier, Standard at $8/user/mo, Plus at $14/user/mo", ["Lightning-fast interface", "AI issue creation", "Cycles and roadmaps", "GitHub integration", "Custom workflows"], ["Fastest PM tool", "Great developer experience", "Clean design"], ["Less flexible than Jira", "Smaller integration ecosystem", "Limited for non-engineering teams"], "https://linear.app", True, True, True, 4.7, ["jira", "clickup-ai", "notion-ai"]),
    ("jira", "Jira", "AI Development", "Atlassian's enterprise project management platform with AI-powered automation and planning.", "Freemium", "Free up to 10 users, Standard at $8.15/user/mo, Premium at $16/user/mo", ["Agile project management", "Custom workflows", "AI-powered automation", "Roadmap planning", "Extensive integrations"], ["Industry standard for engineering", "Highly customizable", "Deep integration ecosystem"], ["Slow and complex interface", "Over-engineered for small teams", "Expensive at scale"], "https://atlassian.com/software/jira", True, True, True, 4.2, ["linear", "clickup-ai", "notion-ai"]),
    ("clickup-ai", "ClickUp AI", "AI Development", "All-in-one productivity platform with AI writing, task management, and project automation.", "Freemium", "Free tier, Unlimited at $7/user/mo, Business at $12/user/mo, AI at $5/user/mo add-on", ["AI writing assistant", "Task management", "Docs and wikis", "Time tracking", "Custom automations"], ["All-in-one workspace", "Affordable pricing", "Feature-rich"], ["Can be overwhelming", "Slower than Linear", "AI is an add-on cost"], "https://clickup.com", True, True, True, 4.3, ["notion-ai", "linear", "jira"]),
    ("retool-ai", "Retool AI", "AI Development", "Low-code platform for building internal tools with AI-powered features and database connections.", "Freemium", "Free tier up to 5 users, Team at $10/user/mo, Business at $50/user/mo", ["Low-code internal tools", "Database connectors", "AI components", "Drag-and-drop builder", "Custom JavaScript"], ["Fast internal tool building", "Wide database support", "AI integration"], ["Expensive for larger teams", "Learning curve", "Limited for external apps"], "https://retool.com", True, True, True, 4.3, ["appsmith", "bubble", "supabase"]),
    ("appsmith", "Appsmith", "AI Development", "Open-source low-code platform for building internal tools with self-hosting support.", "Open Source", "Free self-hosted, Business at $40/user/mo, Enterprise custom", ["Open-source platform", "Self-hosting option", "Database connectors", "Custom JavaScript", "Git version control"], ["Free and open-source", "Self-hosting available", "Good for internal tools"], ["Less polished than Retool", "Smaller community", "Documentation gaps"], "https://appsmith.com", True, True, True, 4.1, ["retool-ai", "bubble", "supabase"]),
    ("github-actions", "GitHub Actions", "AI Development", "GitHub's CI/CD and automation platform with AI-assisted workflow creation.", "Freemium", "Free for public repos, 2000 min/mo free for private, Team at $4/user/mo", ["CI/CD pipelines", "Workflow automation", "Marketplace of actions", "Matrix builds", "Environment management"], ["Free for open source", "Huge action marketplace", "Deep GitHub integration"], ["Complex YAML syntax", "Debugging can be difficult", "Costs add up for private repos"], "https://github.com/features/actions", True, True, True, 4.5, ["gitlab-ci", "vercel", "netlify"]),
    ("gitlab-ci", "GitLab CI", "AI Development", "GitLab's integrated CI/CD platform with AI-powered code suggestions and DevSecOps features.", "Freemium", "Free tier with 400 min/mo, Premium at $29/user/mo, Ultimate at $99/user/mo", ["Integrated CI/CD", "Auto DevOps", "Security scanning", "Container registry", "Code review"], ["Complete DevOps platform", "Integrated security scanning", "Self-hosting option"], ["Complex configuration", "Resource-heavy", "Higher tier pricing"], "https://about.gitlab.com/stages-devops-lifecycle/continuous-integration", True, True, True, 4.3, ["github-actions", "vercel", "datadog"]),
    ("datadog", "Datadog", "AI Development", "Cloud monitoring and observability platform with AI-powered anomaly detection and alerting.", "Paid", "Infrastructure at $15/host/mo, APM at $31/host/mo, Logs at $0.10/GB", ["Infrastructure monitoring", "APM and tracing", "Log management", "AI anomaly detection", "Custom dashboards"], ["Comprehensive observability", "Strong AI-powered alerts", "Wide integration support"], ["Very expensive at scale", "Complex pricing model", "Data ingestion costs"], "https://datadoghq.com", True, True, True, 4.5, ["new-relic", "vercel", "github-actions"]),
    ("new-relic", "New Relic", "AI Development", "Observability platform with AI-powered monitoring and a generous free tier for developers.", "Freemium", "Free tier with 100GB/mo, Standard at $0.30/GB, Pro at $0.50/GB", ["Full-stack observability", "AI assistant for debugging", "Custom dashboards", "Error tracking", "Distributed tracing"], ["Generous free tier", "AI debugging assistant", "Good value"], ["Complex query language", "Can be overwhelming", "Premium features expensive"], "https://newrelic.com", True, True, True, 4.3, ["datadog", "vercel", "github-actions"]),
    ("mongodb-atlas", "MongoDB Atlas", "AI Development", "Managed MongoDB cloud database with vector search and AI application integration features.", "Freemium", "Free tier with 512MB, Serverless from $0.10/million reads, Dedicated from $57/mo", ["Managed MongoDB", "Vector search", "Atlas Search", "Serverless instances", "Multi-cloud deployment"], ["Flexible document model", "Strong vector search", "Good free tier"], ["Can be expensive at scale", "NoSQL learning curve", "Complex pricing"], "https://mongodb.com/atlas", True, True, True, 4.5, ["supabase", "firebase", "pinecone"]),
    ("pinecone", "Pinecone", "AI Development", "Managed vector database built for AI applications with simple APIs and high performance.", "Freemium", "Free tier, Standard at $0.08/hr per pod, Enterprise custom", ["Managed vector database", "Simple REST API", "High-performance similarity search", "Metadata filtering", "Namespace support"], ["Simplest vector DB to use", "High performance", "Reliable managed service"], ["Expensive at scale", "Limited query features", "Vendor lock-in"], "https://pinecone.io", True, True, True, 4.5, ["weaviate", "chromadb", "mongodb-atlas"]),
    ("weaviate", "Weaviate", "AI Development", "Open-source vector database with hybrid search combining vector and keyword capabilities.", "Open Source", "Free self-hosted, Serverless from $0.055/1M dimensions, Enterprise custom", ["Open-source vector DB", "Hybrid search", "Module ecosystem", "GraphQL API", "Multi-tenancy"], ["Open-source flexibility", "Hybrid search capability", "Good documentation"], ["Self-hosting complexity", "Resource intensive", "Learning curve"], "https://weaviate.io", True, True, True, 4.4, ["pinecone", "chromadb", "mongodb-atlas"]),
    ("chromadb", "Chroma", "AI Development", "Lightweight open-source vector database designed for simplicity and fast prototyping.", "Open Source", "Free and open-source, hosted version coming", ["Simple Python API", "In-memory and persistent modes", "OpenAI integration", "Metadata filtering", "Lightweight deployment"], ["Easiest to get started", "Great for prototyping", "Minimal setup"], ["Not production-scale ready", "Limited advanced features", "Smaller community"], "https://trychroma.com", False, True, True, 4.2, ["pinecone", "weaviate", "mongodb-atlas"]),
    ("stripe", "Stripe", "AI Development", "Payment infrastructure platform with AI-powered fraud detection and revenue optimization.", "Paid", "2.9% + $0.30 per transaction, custom enterprise pricing", ["Payment processing", "AI fraud detection", "Billing and subscriptions", "Revenue recovery", "Global payment methods"], ["Best developer experience", "Comprehensive payment features", "Global coverage"], ["Transaction fees add up", "Complex for simple needs", "Account holds can occur"], "https://stripe.com", True, True, True, 4.8, ["lemonsqueezy", "supabase", "vercel"]),
    ("lemonsqueezy", "Lemon Squeezy", "AI Development", "Merchant of record payment platform handling taxes, billing, and subscriptions for SaaS.", "Paid", "5% + $0.50 per transaction, handles all taxes and compliance", ["Merchant of record", "Automatic tax handling", "Subscription management", "License key generation", "Affiliate system"], ["Handles all tax compliance", "Simple to set up", "Great for indie developers"], ["Higher transaction fees", "Fewer features than Stripe", "Smaller ecosystem"], "https://lemonsqueezy.com", True, True, True, 4.3, ["stripe", "vercel", "supabase"]),
    ("coda-ai", "Coda AI", "AI Development", "AI-enhanced document and application platform combining docs, spreadsheets, and automation.", "Freemium", "Free tier, Pro at $10/maker/mo, Team at $30/maker/mo", ["AI document assistant", "Connected tables", "Automation packs", "Cross-doc syncing", "Custom formulas"], ["Powerful doc-as-app concept", "Good automation features", "Flexible data handling"], ["Complex learning curve", "Can be slow with large docs", "Maker-based pricing"], "https://coda.io", True, True, True, 4.2, ["notion-ai", "clickup-ai", "retool-ai"]),

    # AI API / Cloud
    ("anthropic-api", "Anthropic API", "AI API", "API access to Claude models offering frontier reasoning, coding, and analysis capabilities.", "Paid", "Pay-per-token: input $3-15/M tokens, output $15-75/M tokens depending on model", ["Claude model access", "Tool use and function calling", "Vision capabilities", "Streaming responses", "Batch processing"], ["Best reasoning quality", "Strong safety features", "Excellent for coding"], ["Premium pricing for Opus", "Rate limits apply", "Smaller ecosystem than OpenAI"], "https://docs.anthropic.com", True, True, True, 4.7, ["openai-api", "google-ai-api", "cohere"]),
    ("openai-api", "OpenAI API", "AI API", "API access to GPT, DALL-E, Whisper, and other OpenAI models for building AI applications.", "Paid", "Pay-per-token: GPT-4o at $2.50-10/M tokens, other models vary", ["GPT model access", "DALL-E image generation", "Whisper transcription", "Embeddings", "Fine-tuning support"], ["Largest AI API ecosystem", "Most model variety", "Excellent documentation"], ["Can be expensive at scale", "Rate limits on popular models", "Frequent API changes"], "https://platform.openai.com", True, True, True, 4.6, ["anthropic-api", "google-ai-api", "together-ai"]),
    ("google-ai-api", "Google AI API", "AI API", "Access to Gemini models and Google's AI services with generous free tiers and competitive pricing.", "Freemium", "Free tier with generous limits, pay-as-you-go for higher usage", ["Gemini model access", "Multimodal capabilities", "Embeddings API", "Generous free tier", "Google Cloud integration"], ["Competitive pricing", "Strong multimodal support", "Good free tier"], ["Newer API with evolving features", "Less mature ecosystem", "Google Cloud dependency"], "https://ai.google.dev", True, True, True, 4.4, ["openai-api", "anthropic-api", "together-ai"]),
    ("cohere", "Cohere", "AI API", "Enterprise AI platform specializing in text embeddings, search, and retrieval-augmented generation.", "Freemium", "Free trial tier, Production pricing per-token", ["Text embeddings", "Reranking API", "RAG capabilities", "Command model access", "Enterprise deployment options"], ["Best-in-class embeddings", "Strong enterprise features", "Good RAG support"], ["Smaller model selection", "Less general-purpose", "Enterprise pricing opaque"], "https://cohere.com", True, True, True, 4.3, ["openai-api", "anthropic-api", "together-ai"]),
    ("together-ai", "Together AI", "AI API", "Cloud platform for running open-source AI models with fast inference and competitive pricing.", "Paid", "Pay-per-token, typically 50-80% cheaper than proprietary alternatives", ["Open-source model hosting", "Fast inference engine", "Fine-tuning support", "Custom model deployment", "Serverless and dedicated options"], ["Fast open-source inference", "Competitive pricing", "Wide model selection"], ["Only open-source models", "Smaller than major clouds", "Some models less optimized"], "https://together.ai", True, True, True, 4.4, ["replicate", "openai-api", "aws-bedrock"]),
    ("replicate", "Replicate", "AI API", "Cloud platform for running ML models with one-click API deployment and community model sharing.", "Paid", "Pay-per-second of compute, varies by model", ["One-click model APIs", "Community model marketplace", "Custom model hosting", "Streaming support", "Auto-scaling"], ["Easiest model deployment", "Huge model marketplace", "Simple pricing"], ["Per-second billing adds up", "Cold start latency", "Limited control over infrastructure"], "https://replicate.com", True, True, True, 4.4, ["together-ai", "huggingface", "aws-bedrock"]),
    ("huggingface", "Hugging Face", "AI API", "The largest open-source AI platform with model hub, datasets, and inference endpoints.", "Freemium", "Free model hub, Inference Endpoints from $0.06/hr, Enterprise custom", ["150K+ model hub", "Datasets library", "Inference endpoints", "Spaces for demos", "Transformers library"], ["Largest open-source AI hub", "Great community", "Free model access"], ["Inference can be slow", "Complex for beginners", "Enterprise features expensive"], "https://huggingface.co", True, True, True, 4.6, ["replicate", "together-ai", "openai-api"]),
    ("aws-bedrock", "AWS Bedrock", "AI API", "Amazon's managed service for accessing foundation models from multiple providers on AWS.", "Paid", "Pay-per-token, varies by model provider", ["Multi-provider model access", "AWS integration", "Fine-tuning support", "Guardrails", "Knowledge bases"], ["Multiple model providers", "Deep AWS integration", "Enterprise compliance"], ["AWS knowledge required", "Complex pricing", "Vendor lock-in to AWS"], "https://aws.amazon.com/bedrock", True, True, True, 4.4, ["azure-openai", "google-vertex", "together-ai"]),
    ("azure-openai", "Azure OpenAI", "AI API", "Microsoft Azure-hosted OpenAI models with enterprise security, compliance, and data privacy.", "Paid", "Pay-per-token, same model pricing as OpenAI with Azure infrastructure costs", ["OpenAI models on Azure", "Enterprise compliance", "Virtual network support", "Content filtering", "Azure AD integration"], ["Enterprise-grade security", "Data stays in your region", "Azure ecosystem integration"], ["Requires Azure subscription", "Approval process for access", "Complex billing"], "https://azure.microsoft.com/products/ai-services/openai-service", True, True, True, 4.5, ["aws-bedrock", "google-vertex", "openai-api"]),
    ("google-vertex", "Google Vertex AI", "AI API", "Google Cloud's ML platform for building, deploying, and managing AI models at scale.", "Paid", "Pay-per-use, varies by service and model", ["Gemini model access", "AutoML capabilities", "ML pipeline management", "Model monitoring", "Feature store"], ["Comprehensive ML platform", "Strong AutoML", "Google Cloud integration"], ["Complex for beginners", "Expensive for small teams", "Steep learning curve"], "https://cloud.google.com/vertex-ai", False, True, True, 4.4, ["aws-bedrock", "azure-openai", "together-ai"]),

    # AI Legal
    ("harvey-ai", "Harvey AI", "AI Legal", "AI-powered legal assistant for research, document analysis, and contract review.", "Paid", "Enterprise pricing, typically per-seat licensing", ["Legal research AI", "Contract analysis", "Document drafting", "Due diligence automation", "Litigation support"], ["Purpose-built for legal", "Strong document analysis", "Trusted by top firms"], ["Very expensive", "Enterprise-only", "Requires legal expertise to use effectively"], "https://harvey.ai", False, True, True, 4.4, ["casetext", "notion-ai", "chatgpt"]),
    ("casetext", "Casetext CoCounsel", "AI Legal", "Thomson Reuters-backed AI legal assistant for research, document review, and analysis.", "Paid", "Enterprise pricing, included with some Westlaw plans", ["Legal research AI", "Document review", "Deposition preparation", "Contract analysis", "Timeline generation"], ["Thomson Reuters backing", "Strong legal database", "Reliable citations"], ["Expensive enterprise pricing", "Requires Westlaw familiarity", "Limited to legal use cases"], "https://casetext.com", False, True, True, 4.3, ["harvey-ai", "chatgpt", "perplexity"]),

    # Additional to reach 150
    ("mistral", "Mistral", "AI Chatbot", "French AI company offering efficient open-weight models with strong multilingual and European compliance.", "Freemium", "Free tier, API pay-per-token at competitive rates", ["Open-weight models", "European data sovereignty", "Strong multilingual support", "Efficient inference", "API and self-hosting options"], ["European compliance", "Competitive pricing", "Open-weight availability"], ["Smaller ecosystem", "Less polished interface", "Fewer features than ChatGPT"], "https://mistral.ai", True, True, True, 4.4, ["llama", "claude", "chatgpt"]),
    ("llama-4", "Llama 4", "AI Chatbot", "Meta's next-generation open-weight model pushing the boundaries of open-source AI capabilities.", "Open Source", "Free to use, hosting costs vary by provider", ["Open-weight frontier model", "Multiple model sizes", "Commercial license", "Self-hosting support", "Community fine-tuning"], ["Free and open-source", "Near-frontier performance", "Self-hosting freedom"], ["Requires technical setup", "GPU resources needed", "Less support than commercial models"], "https://llama.meta.com", False, True, True, 4.5, ["llama", "mistral", "deepseek"]),
    ("phind", "Phind", "AI Coding", "AI-powered search engine optimized for developers with code generation and technical answers.", "Freemium", "Free tier, Pro at $20/mo with faster models", ["Developer-focused search", "Code generation", "Technical explanations", "Context-aware answers", "VS Code extension"], ["Great for technical questions", "Fast answers with sources", "Free tier is generous"], ["Less accurate for non-code topics", "Smaller model than GPT-4", "Limited integrations"], "https://phind.com", True, True, True, 4.3, ["perplexity", "chatgpt", "cursor"]),
    ("sourcegraph", "Sourcegraph", "AI Coding", "Code intelligence platform with universal code search across repositories and organizations.", "Freemium", "Free for open source, Enterprise at $49/user/mo", ["Universal code search", "Cross-repo navigation", "Code intelligence", "Batch changes", "Code insights"], ["Best code search available", "Cross-repo intelligence", "Enterprise-grade"], ["Expensive for small teams", "Complex setup", "Overkill for small codebases"], "https://sourcegraph.com", True, True, True, 4.4, ["cody", "github-copilot", "cursor"]),
    ("docker-ai", "Docker AI", "AI Development", "Docker's AI-powered tools for container management, debugging, and development optimization.", "Freemium", "Free Personal, Pro at $5/mo, Team at $9/user/mo, Business at $24/user/mo", ["AI-powered debugging", "Container optimization", "Docker Scout security", "Build optimization", "Docker Desktop AI"], ["Essential container tool", "Good AI debugging help", "Wide adoption"], ["AI features still early", "Desktop app can be heavy", "Subscription for teams"], "https://docker.com", True, True, True, 4.4, ["vercel", "github-actions", "datadog"]),
    ("loom-ai", "Loom AI", "AI Development", "AI-powered video messaging platform with automatic titles, summaries, and chapter generation.", "Freemium", "Free Starter, Business at $12.50/creator/mo, Enterprise custom", ["AI video summaries", "Auto-generated titles", "Chapter creation", "Transcription", "Engagement analytics"], ["Great async communication", "AI summaries save time", "Easy to use"], ["Free tier limitations", "Video storage limits", "Dependent on video format"], "https://loom.com", True, True, True, 4.4, ["descript", "otter-ai", "notion-ai"]),
    ("miro-ai", "Miro AI", "AI Development", "AI-enhanced collaborative whiteboard platform for brainstorming, planning, and diagramming.", "Freemium", "Free tier, Starter at $8/user/mo, Business at $16/user/mo", ["AI-powered brainstorming", "Infinite canvas", "Template library", "Real-time collaboration", "Integration ecosystem"], ["Best collaborative whiteboard", "Great for brainstorming", "Wide template selection"], ["Can be slow with large boards", "Premium for AI features", "Learning curve for advanced features"], "https://miro.com", True, True, True, 4.4, ["figma-ai", "notion-ai", "clickup-ai"]),
    ("asana-ai", "Asana AI", "AI Development", "Project management platform with AI-powered task automation, smart status updates, and goals.", "Freemium", "Free tier, Starter at $10.99/user/mo, Advanced at $24.99/user/mo", ["AI smart status", "Task automation", "Goal tracking", "Timeline planning", "Workflow builder"], ["Clean intuitive interface", "Good for non-engineering teams", "Strong goal tracking"], ["Expensive for larger teams", "Less dev-focused than Linear", "AI features premium-only"], "https://asana.com", True, True, True, 4.3, ["monday-ai", "clickup-ai", "linear"]),
    ("monday-ai", "Monday.com AI", "AI Development", "Work management platform with AI assistants for task creation, content generation, and automation.", "Paid", "Basic at $9/user/mo, Standard at $12/user/mo, Pro at $19/user/mo", ["AI task generation", "Workflow automation", "Custom dashboards", "Integration marketplace", "Document collaboration"], ["Highly visual interface", "Flexible for any team", "Good automation"], ["Expensive for small teams", "Can be overwhelming", "AI features still developing"], "https://monday.com", True, True, True, 4.2, ["asana-ai", "clickup-ai", "linear"]),
    ("amplitude-ai", "Amplitude", "AI Analytics", "Product analytics platform with AI-powered insights, user behavior tracking, and experimentation.", "Freemium", "Free Starter plan, Growth and Enterprise custom pricing", ["AI-powered insights", "User behavior analytics", "Funnel analysis", "Cohort analysis", "A/B testing"], ["Strong product analytics", "Good AI insight generation", "Free tier available"], ["Complex for beginners", "Expensive growth tier", "Implementation effort"], "https://amplitude.com", True, True, True, 4.4, ["mixpanel-ai", "power-bi", "julius-ai"]),
    ("mixpanel-ai", "Mixpanel", "AI Analytics", "Event-based product analytics platform with AI reports and user journey tracking.", "Freemium", "Free tier up to 20M events, Growth at $20/mo, Enterprise custom", ["Event-based analytics", "AI-generated reports", "User journey mapping", "Retention analysis", "Custom dashboards"], ["Strong event tracking", "Good free tier", "Intuitive reports"], ["Complex implementation", "Expensive at scale", "Data modeling learning curve"], "https://mixpanel.com", True, True, True, 4.3, ["amplitude-ai", "power-bi", "julius-ai"]),
    ("segment-ai", "Segment", "AI Analytics", "Customer data platform that collects, unifies, and routes data to analytics and marketing tools.", "Freemium", "Free tier up to 1000 visitors/mo, Team at $120/mo, Business custom", ["Data collection and routing", "Identity resolution", "300+ integrations", "Protocols for data quality", "Audiences and computed traits"], ["Best data infrastructure", "Wide integration ecosystem", "Clean data routing"], ["Expensive for startups", "Complex to set up properly", "Free tier very limited"], "https://segment.com", False, True, True, 4.4, ["amplitude-ai", "mixpanel-ai", "datadog"]),
    ("mem-ai", "Mem AI", "AI Development", "AI-powered knowledge management that automatically organizes and surfaces relevant notes.", "Freemium", "Free tier, Premium at $14.99/mo, Teams at $19.99/user/mo", ["AI-powered note organization", "Smart search", "Meeting note integration", "Knowledge graph", "Auto-tagging"], ["Smart auto-organization", "Good search capabilities", "Clean interface"], ["Limited formatting options", "Import capabilities lacking", "Smaller ecosystem"], "https://mem.ai", True, True, True, 4.1, ["notion-ai", "coda-ai", "clickup-ai"]),
    ("reclaim-ai", "Reclaim AI", "AI Development", "AI-powered calendar management tool that optimizes scheduling for habits, tasks, and meetings.", "Freemium", "Free tier, Starter at $8/user/mo, Business at $12/user/mo", ["AI calendar optimization", "Smart habit scheduling", "Task auto-scheduling", "Meeting optimization", "Buffer time management"], ["Intelligent calendar management", "Reduces scheduling friction", "Good free tier"], ["Limited to Google Calendar mainly", "Can over-schedule", "Learning period needed"], "https://reclaim.ai", True, True, True, 4.3, ["asana-ai", "clickup-ai", "notion-ai"]),
    ("taskade-ai", "Taskade AI", "AI Development", "AI-powered workspace combining task management, docs, and AI agent automation.", "Freemium", "Free tier, Pro at $8/user/mo, Business at $16/user/mo", ["AI agent workspace", "Task and project management", "AI document generation", "Workflow automation", "Real-time collaboration"], ["All-in-one AI workspace", "Affordable pricing", "Multiple AI features"], ["Less mature than competitors", "Can feel cluttered", "Smaller user base"], "https://taskade.com", True, True, True, 4.1, ["notion-ai", "clickup-ai", "asana-ai"]),
    ("krisp-ai", "Krisp AI", "AI Audio", "AI-powered noise cancellation and meeting assistant for cleaner calls and meeting notes.", "Freemium", "Free tier with 60 min/day, Pro at $8/mo, Enterprise custom", ["AI noise cancellation", "Meeting transcription", "Meeting summaries", "Action item extraction", "Works with any app"], ["Excellent noise cancellation", "App-agnostic solution", "Good transcription"], ["Free tier daily limit", "CPU-intensive", "Occasional audio artifacts"], "https://krisp.ai", True, True, True, 4.3, ["otter-ai", "fireflies", "descript"]),
    ("postman-ai", "Postman AI", "AI Development", "API development platform with AI-powered test generation, documentation, and API exploration.", "Freemium", "Free tier, Basic at $14/user/mo, Professional at $29/user/mo", ["AI test generation", "API documentation AI", "Collection runner", "Mock servers", "API monitoring"], ["Essential API tool", "AI speeds up testing", "Great collaboration"], ["AI features still evolving", "Can be resource-heavy", "Free tier limits"], "https://postman.com", True, True, True, 4.5, ["docker-ai", "github-actions", "vercel"]),
    ("semantic-kernel", "Semantic Kernel", "AI Agent Framework", "Microsoft's open-source SDK for integrating LLMs into applications with plugins, planners, and memory.", "Open Source", "Free, Microsoft-backed open-source project", ["Plugin-based architecture", "Multi-LLM provider support", "Planner for task orchestration", "Memory and embeddings integration", "C# and Python SDKs"], ["Strong Microsoft ecosystem integration", "Clean plugin architecture", "Enterprise-ready patterns"], ["Smaller community than LangChain", "C#-first with Python catching up", "Documentation can lag behind features"], "https://learn.microsoft.com/semantic-kernel", True, True, True, 4.3, ["langchain", "autogen", "crewai"]),
]

def format_tool(t):
    slug, name, cat, desc, pricing, pricingDetail, features, pros, cons, url, altP, priceP, reviewP, rating, alts = t
    feat_str = ", ".join(f'"{f}"' for f in features)
    pros_str = ", ".join(f'"{p}"' for p in pros)
    cons_str = ", ".join(f'"{c}"' for c in cons)
    alts_str = ", ".join(f'"{a}"' for a in alts)
    return (
        f'  {{ slug: "{slug}", name: "{name}", category: "{cat}", '
        f'description: "{desc}", pricing: "{pricing}", '
        f'pricingDetail: "{pricingDetail}", '
        f'features: [{feat_str}], '
        f'pros: [{pros_str}], '
        f'cons: [{cons_str}], '
        f'url: "{url}", '
        f'hasAlternativePage: {"true" if altP else "false"}, '
        f'hasPricingPage: {"true" if priceP else "false"}, '
        f'hasReviewPage: {"true" if reviewP else "false"}, '
        f'rating: {rating}, '
        f'alternatives: [{alts_str}] }},'
    )

lines = ['import type { Tool } from "@/types";', '', 'export const tools: Tool[] = [']
for t in TOOLS:
    lines.append(format_tool(t))
lines.append('];')
lines.append('')

content = '\n'.join(lines)
with open('/Users/adda247/personal/shipsquad/shipsquad-front/src/data/tools.ts', 'w') as f:
    f.write(content)

print(f"Written {len(TOOLS)} tools to tools.ts ({len(content)} bytes)")

# Verify all required slugs are present
import re
with open('/Users/adda247/personal/shipsquad/shipsquad-front/src/data/comparisons.ts') as f:
    comp_content = f.read()
tool_section = comp_content[comp_content.index('const toolData'):comp_content.index('const traditionalData')]
required = set()
for match in re.finditer(r'\["([^"]+)",\s*"[^"]+",\s*"([^"]+)"', tool_section):
    required.add(match.group(1))
    required.add(match.group(2))

tool_slugs = set(t[0] for t in TOOLS)
missing = required - tool_slugs
if missing:
    print(f"MISSING {len(missing)} required slugs: {sorted(missing)}")
else:
    print("All required comparison slugs present!")
print(f"Extra tools beyond required: {len(tool_slugs - required)}")
